// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.templates

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TemplateListResponseTest {

    @Test
    fun create() {
        val templateListResponse =
            TemplateListResponse.builder()
                .offset(0L)
                .addTemplate(
                    TemplateListResponse.Template.builder()
                        .id("id")
                        .createdAt("created_at")
                        .image("image")
                        .name("name")
                        .proxyConfig(
                            TemplateListResponse.Template.ProxyConfig.builder()
                                .accessControl(
                                    TemplateListResponse.Template.ProxyConfig.AccessControl
                                        .builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    TemplateListResponse.Template.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .addRequestHeader(
                                            TemplateListResponse.Template.ProxyConfig.Callback
                                                .RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    TemplateListResponse.Template.ProxyConfig
                                                        .Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    TemplateListResponse.Template.ProxyConfig.Rule.builder()
                                        .addMatchHost("string")
                                        .name("name")
                                        .enabled(true)
                                        .addHeader(
                                            TemplateListResponse.Template.ProxyConfig.Rule.Header
                                                .builder()
                                                .name("name")
                                                .type(
                                                    TemplateListResponse.Template.ProxyConfig.Rule
                                                        .Header
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchPath("string")
                                        .build()
                                )
                                .build()
                        )
                        .registryId("registry_id")
                        .registryName("registry_name")
                        .resources(
                            TemplateListResponse.Template.Resources.builder()
                                .cpu("cpu")
                                .memory("memory")
                                .storage("storage")
                                .build()
                        )
                        .updatedAt("updated_at")
                        .addVolumeMount(
                            TemplateListResponse.Template.VolumeMount.builder()
                                .mountPath("mount_path")
                                .volumeName("volume_name")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(templateListResponse.offset()).contains(0L)
        assertThat(templateListResponse.templates().getOrNull())
            .containsExactly(
                TemplateListResponse.Template.builder()
                    .id("id")
                    .createdAt("created_at")
                    .image("image")
                    .name("name")
                    .proxyConfig(
                        TemplateListResponse.Template.ProxyConfig.builder()
                            .accessControl(
                                TemplateListResponse.Template.ProxyConfig.AccessControl.builder()
                                    .addAllowList("string")
                                    .addDenyList("string")
                                    .build()
                            )
                            .addCallback(
                                TemplateListResponse.Template.ProxyConfig.Callback.builder()
                                    .addMatchHost("string")
                                    .ttlSeconds(60L)
                                    .url("url")
                                    .addRequestHeader(
                                        TemplateListResponse.Template.ProxyConfig.Callback
                                            .RequestHeader
                                            .builder()
                                            .name("name")
                                            .type(
                                                TemplateListResponse.Template.ProxyConfig.Callback
                                                    .RequestHeader
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addNoProxy("string")
                            .addRule(
                                TemplateListResponse.Template.ProxyConfig.Rule.builder()
                                    .addMatchHost("string")
                                    .name("name")
                                    .enabled(true)
                                    .addHeader(
                                        TemplateListResponse.Template.ProxyConfig.Rule.Header
                                            .builder()
                                            .name("name")
                                            .type(
                                                TemplateListResponse.Template.ProxyConfig.Rule
                                                    .Header
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .addMatchPath("string")
                                    .build()
                            )
                            .build()
                    )
                    .registryId("registry_id")
                    .registryName("registry_name")
                    .resources(
                        TemplateListResponse.Template.Resources.builder()
                            .cpu("cpu")
                            .memory("memory")
                            .storage("storage")
                            .build()
                    )
                    .updatedAt("updated_at")
                    .addVolumeMount(
                        TemplateListResponse.Template.VolumeMount.builder()
                            .mountPath("mount_path")
                            .volumeName("volume_name")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val templateListResponse =
            TemplateListResponse.builder()
                .offset(0L)
                .addTemplate(
                    TemplateListResponse.Template.builder()
                        .id("id")
                        .createdAt("created_at")
                        .image("image")
                        .name("name")
                        .proxyConfig(
                            TemplateListResponse.Template.ProxyConfig.builder()
                                .accessControl(
                                    TemplateListResponse.Template.ProxyConfig.AccessControl
                                        .builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    TemplateListResponse.Template.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .addRequestHeader(
                                            TemplateListResponse.Template.ProxyConfig.Callback
                                                .RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    TemplateListResponse.Template.ProxyConfig
                                                        .Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    TemplateListResponse.Template.ProxyConfig.Rule.builder()
                                        .addMatchHost("string")
                                        .name("name")
                                        .enabled(true)
                                        .addHeader(
                                            TemplateListResponse.Template.ProxyConfig.Rule.Header
                                                .builder()
                                                .name("name")
                                                .type(
                                                    TemplateListResponse.Template.ProxyConfig.Rule
                                                        .Header
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchPath("string")
                                        .build()
                                )
                                .build()
                        )
                        .registryId("registry_id")
                        .registryName("registry_name")
                        .resources(
                            TemplateListResponse.Template.Resources.builder()
                                .cpu("cpu")
                                .memory("memory")
                                .storage("storage")
                                .build()
                        )
                        .updatedAt("updated_at")
                        .addVolumeMount(
                            TemplateListResponse.Template.VolumeMount.builder()
                                .mountPath("mount_path")
                                .volumeName("volume_name")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedTemplateListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(templateListResponse),
                jacksonTypeRef<TemplateListResponse>(),
            )

        assertThat(roundtrippedTemplateListResponse).isEqualTo(templateListResponse)
    }
}
