version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major
    open-pull-requests-limit: 5
