// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.orgs.current

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class OrganizationConfigTest {

    @Test
    fun create() {
        val organizationConfig =
            OrganizationConfig.builder()
                .allowCustomIframes(true)
                .canAddSeats(true)
                .canDisablePublicSharing(true)
                .canServeDatasets(true)
                .canUseAbac(true)
                .canUseAgentBuilder(true)
                .canUseBulkExport(true)
                .canUseLanggraphCloud(true)
                .canUseRbac(true)
                .canUseSamlSso(true)
                .clioEnabled(true)
                .datadogRumSessionSampleRate(0L)
                .demoLgpNewGraphEnabled(true)
                .enableAlignEvaluators(true)
                .enableIncludeExtendedStats(true)
                .enableLanggraphPricing(true)
                .enableLgpListenersPage(true)
                .enableMarkdownInTracing(true)
                .enableMonthlyUsageCharts(true)
                .enableOrgUsageCharts(true)
                .enablePricingRedesign(true)
                .enableQueryingV2Endpoints(true)
                .enableRunTreeStreaming(true)
                .enableThreadViewPlayground(true)
                .enableThreadsImprovements(true)
                .kvDatasetMessageSupport(true)
                .langgraphDeployOwnCloudEnabled(true)
                .langgraphEnterpriseEnabled(true)
                .langgraphRemoteReconcilerEnabled(true)
                .langsmithAlertsLegacyPocEnabled(true)
                .langsmithAlertsPocEnabled(true)
                .langsmithExperimentalSearchEnabled(true)
                .lgpTemplatesEnabled(true)
                .maxFreeLanggraphCloudDeployments(0L)
                .maxIdentities(0L)
                .maxLanggraphCloudDeployments(0L)
                .maxPromptWebhooks(0L)
                .maxThreadEvaluatorsPerTenant(0L)
                .maxWorkspaces(0L)
                .newRuleEvaluatorCreationVersion(0L)
                .partnerPlanApprovalDate("partner_plan_approval_date")
                .playgroundEvaluatorStrategy("playground_evaluator_strategy")
                .premierPlanApprovalDate("premier_plan_approval_date")
                .promptOptimizationJobsEnabled(true)
                .requireCodeEvaluatorLanguageField(true)
                .showPlaygroundPromptCanvas(true)
                .showUpdatedResourceTags(true)
                .showUpdatedSidenav(true)
                .startupPlanApprovalDate("startup_plan_approval_date")
                .tenantSkipTopkFacets(true)
                .threadEvaluatorsEnabled(true)
                .useExactSearchForPrompts(true)
                .usePythonPlaygroundService(true)
                .build()

        assertThat(organizationConfig.allowCustomIframes()).contains(true)
        assertThat(organizationConfig.canAddSeats()).contains(true)
        assertThat(organizationConfig.canDisablePublicSharing()).contains(true)
        assertThat(organizationConfig.canServeDatasets()).contains(true)
        assertThat(organizationConfig.canUseAbac()).contains(true)
        assertThat(organizationConfig.canUseAgentBuilder()).contains(true)
        assertThat(organizationConfig.canUseBulkExport()).contains(true)
        assertThat(organizationConfig.canUseLanggraphCloud()).contains(true)
        assertThat(organizationConfig.canUseRbac()).contains(true)
        assertThat(organizationConfig.canUseSamlSso()).contains(true)
        assertThat(organizationConfig.clioEnabled()).contains(true)
        assertThat(organizationConfig.datadogRumSessionSampleRate()).contains(0L)
        assertThat(organizationConfig.demoLgpNewGraphEnabled()).contains(true)
        assertThat(organizationConfig.enableAlignEvaluators()).contains(true)
        assertThat(organizationConfig.enableIncludeExtendedStats()).contains(true)
        assertThat(organizationConfig.enableLanggraphPricing()).contains(true)
        assertThat(organizationConfig.enableLgpListenersPage()).contains(true)
        assertThat(organizationConfig.enableMarkdownInTracing()).contains(true)
        assertThat(organizationConfig.enableMonthlyUsageCharts()).contains(true)
        assertThat(organizationConfig.enableOrgUsageCharts()).contains(true)
        assertThat(organizationConfig.enablePricingRedesign()).contains(true)
        assertThat(organizationConfig.enableQueryingV2Endpoints()).contains(true)
        assertThat(organizationConfig.enableRunTreeStreaming()).contains(true)
        assertThat(organizationConfig.enableThreadViewPlayground()).contains(true)
        assertThat(organizationConfig.enableThreadsImprovements()).contains(true)
        assertThat(organizationConfig.kvDatasetMessageSupport()).contains(true)
        assertThat(organizationConfig.langgraphDeployOwnCloudEnabled()).contains(true)
        assertThat(organizationConfig.langgraphEnterpriseEnabled()).contains(true)
        assertThat(organizationConfig.langgraphRemoteReconcilerEnabled()).contains(true)
        assertThat(organizationConfig.langsmithAlertsLegacyPocEnabled()).contains(true)
        assertThat(organizationConfig.langsmithAlertsPocEnabled()).contains(true)
        assertThat(organizationConfig.langsmithExperimentalSearchEnabled()).contains(true)
        assertThat(organizationConfig.lgpTemplatesEnabled()).contains(true)
        assertThat(organizationConfig.maxFreeLanggraphCloudDeployments()).contains(0L)
        assertThat(organizationConfig.maxIdentities()).contains(0L)
        assertThat(organizationConfig.maxLanggraphCloudDeployments()).contains(0L)
        assertThat(organizationConfig.maxPromptWebhooks()).contains(0L)
        assertThat(organizationConfig.maxThreadEvaluatorsPerTenant()).contains(0L)
        assertThat(organizationConfig.maxWorkspaces()).contains(0L)
        assertThat(organizationConfig.newRuleEvaluatorCreationVersion()).contains(0L)
        assertThat(organizationConfig.partnerPlanApprovalDate())
            .contains("partner_plan_approval_date")
        assertThat(organizationConfig.playgroundEvaluatorStrategy())
            .contains("playground_evaluator_strategy")
        assertThat(organizationConfig.premierPlanApprovalDate())
            .contains("premier_plan_approval_date")
        assertThat(organizationConfig.promptOptimizationJobsEnabled()).contains(true)
        assertThat(organizationConfig.requireCodeEvaluatorLanguageField()).contains(true)
        assertThat(organizationConfig.showPlaygroundPromptCanvas()).contains(true)
        assertThat(organizationConfig.showUpdatedResourceTags()).contains(true)
        assertThat(organizationConfig.showUpdatedSidenav()).contains(true)
        assertThat(organizationConfig.startupPlanApprovalDate())
            .contains("startup_plan_approval_date")
        assertThat(organizationConfig.tenantSkipTopkFacets()).contains(true)
        assertThat(organizationConfig.threadEvaluatorsEnabled()).contains(true)
        assertThat(organizationConfig.useExactSearchForPrompts()).contains(true)
        assertThat(organizationConfig.usePythonPlaygroundService()).contains(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val organizationConfig =
            OrganizationConfig.builder()
                .allowCustomIframes(true)
                .canAddSeats(true)
                .canDisablePublicSharing(true)
                .canServeDatasets(true)
                .canUseAbac(true)
                .canUseAgentBuilder(true)
                .canUseBulkExport(true)
                .canUseLanggraphCloud(true)
                .canUseRbac(true)
                .canUseSamlSso(true)
                .clioEnabled(true)
                .datadogRumSessionSampleRate(0L)
                .demoLgpNewGraphEnabled(true)
                .enableAlignEvaluators(true)
                .enableIncludeExtendedStats(true)
                .enableLanggraphPricing(true)
                .enableLgpListenersPage(true)
                .enableMarkdownInTracing(true)
                .enableMonthlyUsageCharts(true)
                .enableOrgUsageCharts(true)
                .enablePricingRedesign(true)
                .enableQueryingV2Endpoints(true)
                .enableRunTreeStreaming(true)
                .enableThreadViewPlayground(true)
                .enableThreadsImprovements(true)
                .kvDatasetMessageSupport(true)
                .langgraphDeployOwnCloudEnabled(true)
                .langgraphEnterpriseEnabled(true)
                .langgraphRemoteReconcilerEnabled(true)
                .langsmithAlertsLegacyPocEnabled(true)
                .langsmithAlertsPocEnabled(true)
                .langsmithExperimentalSearchEnabled(true)
                .lgpTemplatesEnabled(true)
                .maxFreeLanggraphCloudDeployments(0L)
                .maxIdentities(0L)
                .maxLanggraphCloudDeployments(0L)
                .maxPromptWebhooks(0L)
                .maxThreadEvaluatorsPerTenant(0L)
                .maxWorkspaces(0L)
                .newRuleEvaluatorCreationVersion(0L)
                .partnerPlanApprovalDate("partner_plan_approval_date")
                .playgroundEvaluatorStrategy("playground_evaluator_strategy")
                .premierPlanApprovalDate("premier_plan_approval_date")
                .promptOptimizationJobsEnabled(true)
                .requireCodeEvaluatorLanguageField(true)
                .showPlaygroundPromptCanvas(true)
                .showUpdatedResourceTags(true)
                .showUpdatedSidenav(true)
                .startupPlanApprovalDate("startup_plan_approval_date")
                .tenantSkipTopkFacets(true)
                .threadEvaluatorsEnabled(true)
                .useExactSearchForPrompts(true)
                .usePythonPlaygroundService(true)
                .build()

        val roundtrippedOrganizationConfig =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(organizationConfig),
                jacksonTypeRef<OrganizationConfig>(),
            )

        assertThat(roundtrippedOrganizationConfig).isEqualTo(organizationConfig)
    }
}
