plugins {
    id("langchain.java")
    id("langchain.publish")
}

// Suppress obsolete Java 8 warnings since we're using Java 21 toolchain but targeting Java 8
tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-Xlint:-options")
}

// Customize POM for wrappers module
configure<com.vanniktech.maven.publish.MavenPublishBaseExtension> {
    pom {
        name.set("LangSmith Java Wrappers")
        description.set("OpenTelemetry integration wrappers for LangSmith in Java. " +
            "This package provides OpenTelemetry wrappers for AI model clients to enable " +
            "automatic tracing and monitoring with LangSmith.")
    }
}

dependencies {
    // OpenAI Java SDK - Required for examples to run
    // The wrappers wrap the OpenAI SDK generated by Stainless
    // Users should add this dependency when using the wrappers in their own projects
    // Example: implementation("com.openai:openai-java:4.6.1")
    implementation("com.openai:openai-java:4.6.1")

    // OpenTelemetry API
    api("io.opentelemetry:opentelemetry-api:1.32.0")
    api("io.opentelemetry:opentelemetry-context:1.32.0")

    // OpenTelemetry SDK (for configuring exporters)
    implementation("io.opentelemetry:opentelemetry-sdk:1.32.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.32.0")
    // Note: OtlpHttpSpanExporter should be in opentelemetry-exporter-otlp, but if not found,
    // we may need to check the actual package structure

    // Test dependencies
    testImplementation("com.openai:openai-java:4.6.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.3")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.3")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Task to run examples
tasks.register<JavaExec>("runExample") {
    group = "application"
    description = "Run an example class"

    classpath = sourceSets["main"].runtimeClasspath

    // Get the example class from project property, or use default
    val exampleClass = project.findProperty("exampleClass") as String?
    mainClass.set(exampleClass ?: "com.langchain.smith.wrappers.openai.examples.SimpleChatCompletionExample")

    // Pass through environment variables (especially OPENAI_API_KEY, LANGSMITH_API_KEY, etc.)
    environment.putAll(System.getenv())
}

