// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SandboxListResponseTest {

    @Test
    fun create() {
        val sandboxListResponse =
            SandboxListResponse.builder()
                .offset(0L)
                .addSandbox(
                    SandboxResponse.builder()
                        .id("id")
                        .createdAt("created_at")
                        .createdBy("created_by")
                        .dataplaneUrl("dataplane_url")
                        .deleteAfterStopSeconds(0L)
                        .fsCapacityBytes(0L)
                        .idleTtlSeconds(0L)
                        .memBytes(0L)
                        .mountConfig(
                            SandboxResponse.MountConfig.builder()
                                .auth(
                                    SandboxResponse.MountConfig.Auth.builder()
                                        .aws(
                                            SandboxResponse.MountConfig.Auth.Aws.builder()
                                                .accessKeyId(
                                                    SandboxResponse.MountConfig.Auth.Aws.AccessKeyId
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    SandboxResponse.MountConfig.Auth.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .gcp(
                                            SandboxResponse.MountConfig.Auth.Gcp.builder()
                                                .serviceAccountJson(
                                                    SandboxResponse.MountConfig.Auth.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .addMount(
                                    SandboxResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .builder()
                                        .id("id")
                                        .mountPath("mount_path")
                                        .s3(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .S3
                                                .builder()
                                                .bucket("bucket")
                                                .region("region")
                                                .endpointUrl("endpoint_url")
                                                .pathStyle(true)
                                                .prefix("prefix")
                                                .build()
                                        )
                                        .type(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Type
                                                .S3
                                        )
                                        .cache(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Cache
                                                .builder()
                                                .maxSizeBytes(0L)
                                                .writebackSeconds(0L)
                                                .build()
                                        )
                                        .gcs(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Gcs
                                                .builder()
                                                .bucket("bucket")
                                                .prefix("prefix")
                                                .build()
                                        )
                                        .git(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Git
                                                .builder()
                                                .remoteUrl("remote_url")
                                                .ref(
                                                    SandboxResponse.MountConfig.Mount
                                                        .SandboxapiS3BucketMountSpec
                                                        .Git
                                                        .Ref
                                                        .builder()
                                                        .name("name")
                                                        .type(
                                                            SandboxResponse.MountConfig.Mount
                                                                .SandboxapiS3BucketMountSpec
                                                                .Git
                                                                .Ref
                                                                .Type
                                                                .BRANCH
                                                        )
                                                        .build()
                                                )
                                                .refreshIntervalSeconds(1L)
                                                .build()
                                        )
                                        .readOnly(true)
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .proxyConfig(
                            SandboxResponse.ProxyConfig.builder()
                                .accessControl(
                                    SandboxResponse.ProxyConfig.AccessControl.builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    SandboxResponse.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .fullRequest(true)
                                        .addRequestHeader(
                                            SandboxResponse.ProxyConfig.Callback.RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    SandboxResponse.ProxyConfig.Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    SandboxResponse.ProxyConfig.Rule.builder()
                                        .name("name")
                                        .aws(
                                            SandboxResponse.ProxyConfig.Rule.Aws.builder()
                                                .accessKeyId(
                                                    SandboxResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    SandboxResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .enabled(true)
                                        .gcp(
                                            SandboxResponse.ProxyConfig.Rule.Gcp.builder()
                                                .addScope("string")
                                                .serviceAccountJson(
                                                    SandboxResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            SandboxResponse.ProxyConfig.Rule.Header.builder()
                                                .name("name")
                                                .type(
                                                    SandboxResponse.ProxyConfig.Rule.Header.Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchHost("string")
                                        .addMatchPath("string")
                                        .type("type")
                                        .build()
                                )
                                .build()
                        )
                        .sizeClass("size_class")
                        .snapshotId("snapshot_id")
                        .status("status")
                        .statusMessage("status_message")
                        .stoppedAt("stopped_at")
                        .updatedAt("updated_at")
                        .updatedBy("updated_by")
                        .vcpus(0L)
                        .build()
                )
                .build()

        assertThat(sandboxListResponse.offset()).contains(0L)
        assertThat(sandboxListResponse.sandboxes().getOrNull())
            .containsExactly(
                SandboxResponse.builder()
                    .id("id")
                    .createdAt("created_at")
                    .createdBy("created_by")
                    .dataplaneUrl("dataplane_url")
                    .deleteAfterStopSeconds(0L)
                    .fsCapacityBytes(0L)
                    .idleTtlSeconds(0L)
                    .memBytes(0L)
                    .mountConfig(
                        SandboxResponse.MountConfig.builder()
                            .auth(
                                SandboxResponse.MountConfig.Auth.builder()
                                    .aws(
                                        SandboxResponse.MountConfig.Auth.Aws.builder()
                                            .accessKeyId(
                                                SandboxResponse.MountConfig.Auth.Aws.AccessKeyId
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.MountConfig.Auth.Aws
                                                            .AccessKeyId
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .secretAccessKey(
                                                SandboxResponse.MountConfig.Auth.Aws.SecretAccessKey
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.MountConfig.Auth.Aws
                                                            .SecretAccessKey
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .gcp(
                                        SandboxResponse.MountConfig.Auth.Gcp.builder()
                                            .serviceAccountJson(
                                                SandboxResponse.MountConfig.Auth.Gcp
                                                    .ServiceAccountJson
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.MountConfig.Auth.Gcp
                                                            .ServiceAccountJson
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .addMount(
                                SandboxResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                    .builder()
                                    .id("id")
                                    .mountPath("mount_path")
                                    .s3(
                                        SandboxResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .S3
                                            .builder()
                                            .bucket("bucket")
                                            .region("region")
                                            .endpointUrl("endpoint_url")
                                            .pathStyle(true)
                                            .prefix("prefix")
                                            .build()
                                    )
                                    .type(
                                        SandboxResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Type
                                            .S3
                                    )
                                    .cache(
                                        SandboxResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Cache
                                            .builder()
                                            .maxSizeBytes(0L)
                                            .writebackSeconds(0L)
                                            .build()
                                    )
                                    .gcs(
                                        SandboxResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Gcs
                                            .builder()
                                            .bucket("bucket")
                                            .prefix("prefix")
                                            .build()
                                    )
                                    .git(
                                        SandboxResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Git
                                            .builder()
                                            .remoteUrl("remote_url")
                                            .ref(
                                                SandboxResponse.MountConfig.Mount
                                                    .SandboxapiS3BucketMountSpec
                                                    .Git
                                                    .Ref
                                                    .builder()
                                                    .name("name")
                                                    .type(
                                                        SandboxResponse.MountConfig.Mount
                                                            .SandboxapiS3BucketMountSpec
                                                            .Git
                                                            .Ref
                                                            .Type
                                                            .BRANCH
                                                    )
                                                    .build()
                                            )
                                            .refreshIntervalSeconds(1L)
                                            .build()
                                    )
                                    .readOnly(true)
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .proxyConfig(
                        SandboxResponse.ProxyConfig.builder()
                            .accessControl(
                                SandboxResponse.ProxyConfig.AccessControl.builder()
                                    .addAllowList("string")
                                    .addDenyList("string")
                                    .build()
                            )
                            .addCallback(
                                SandboxResponse.ProxyConfig.Callback.builder()
                                    .addMatchHost("string")
                                    .ttlSeconds(60L)
                                    .url("url")
                                    .fullRequest(true)
                                    .addRequestHeader(
                                        SandboxResponse.ProxyConfig.Callback.RequestHeader.builder()
                                            .name("name")
                                            .type(
                                                SandboxResponse.ProxyConfig.Callback.RequestHeader
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addNoProxy("string")
                            .addRule(
                                SandboxResponse.ProxyConfig.Rule.builder()
                                    .name("name")
                                    .aws(
                                        SandboxResponse.ProxyConfig.Rule.Aws.builder()
                                            .accessKeyId(
                                                SandboxResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.ProxyConfig.Rule.Aws
                                                            .AccessKeyId
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .secretAccessKey(
                                                SandboxResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.ProxyConfig.Rule.Aws
                                                            .SecretAccessKey
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .enabled(true)
                                    .gcp(
                                        SandboxResponse.ProxyConfig.Rule.Gcp.builder()
                                            .addScope("string")
                                            .serviceAccountJson(
                                                SandboxResponse.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .builder()
                                                    .type(
                                                        SandboxResponse.ProxyConfig.Rule.Gcp
                                                            .ServiceAccountJson
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addHeader(
                                        SandboxResponse.ProxyConfig.Rule.Header.builder()
                                            .name("name")
                                            .type(
                                                SandboxResponse.ProxyConfig.Rule.Header.Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .addMatchHost("string")
                                    .addMatchPath("string")
                                    .type("type")
                                    .build()
                            )
                            .build()
                    )
                    .sizeClass("size_class")
                    .snapshotId("snapshot_id")
                    .status("status")
                    .statusMessage("status_message")
                    .stoppedAt("stopped_at")
                    .updatedAt("updated_at")
                    .updatedBy("updated_by")
                    .vcpus(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val sandboxListResponse =
            SandboxListResponse.builder()
                .offset(0L)
                .addSandbox(
                    SandboxResponse.builder()
                        .id("id")
                        .createdAt("created_at")
                        .createdBy("created_by")
                        .dataplaneUrl("dataplane_url")
                        .deleteAfterStopSeconds(0L)
                        .fsCapacityBytes(0L)
                        .idleTtlSeconds(0L)
                        .memBytes(0L)
                        .mountConfig(
                            SandboxResponse.MountConfig.builder()
                                .auth(
                                    SandboxResponse.MountConfig.Auth.builder()
                                        .aws(
                                            SandboxResponse.MountConfig.Auth.Aws.builder()
                                                .accessKeyId(
                                                    SandboxResponse.MountConfig.Auth.Aws.AccessKeyId
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    SandboxResponse.MountConfig.Auth.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .gcp(
                                            SandboxResponse.MountConfig.Auth.Gcp.builder()
                                                .serviceAccountJson(
                                                    SandboxResponse.MountConfig.Auth.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.MountConfig.Auth.Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .addMount(
                                    SandboxResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .builder()
                                        .id("id")
                                        .mountPath("mount_path")
                                        .s3(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .S3
                                                .builder()
                                                .bucket("bucket")
                                                .region("region")
                                                .endpointUrl("endpoint_url")
                                                .pathStyle(true)
                                                .prefix("prefix")
                                                .build()
                                        )
                                        .type(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Type
                                                .S3
                                        )
                                        .cache(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Cache
                                                .builder()
                                                .maxSizeBytes(0L)
                                                .writebackSeconds(0L)
                                                .build()
                                        )
                                        .gcs(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Gcs
                                                .builder()
                                                .bucket("bucket")
                                                .prefix("prefix")
                                                .build()
                                        )
                                        .git(
                                            SandboxResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Git
                                                .builder()
                                                .remoteUrl("remote_url")
                                                .ref(
                                                    SandboxResponse.MountConfig.Mount
                                                        .SandboxapiS3BucketMountSpec
                                                        .Git
                                                        .Ref
                                                        .builder()
                                                        .name("name")
                                                        .type(
                                                            SandboxResponse.MountConfig.Mount
                                                                .SandboxapiS3BucketMountSpec
                                                                .Git
                                                                .Ref
                                                                .Type
                                                                .BRANCH
                                                        )
                                                        .build()
                                                )
                                                .refreshIntervalSeconds(1L)
                                                .build()
                                        )
                                        .readOnly(true)
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .proxyConfig(
                            SandboxResponse.ProxyConfig.builder()
                                .accessControl(
                                    SandboxResponse.ProxyConfig.AccessControl.builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    SandboxResponse.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .fullRequest(true)
                                        .addRequestHeader(
                                            SandboxResponse.ProxyConfig.Callback.RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    SandboxResponse.ProxyConfig.Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    SandboxResponse.ProxyConfig.Rule.builder()
                                        .name("name")
                                        .aws(
                                            SandboxResponse.ProxyConfig.Rule.Aws.builder()
                                                .accessKeyId(
                                                    SandboxResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    SandboxResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .enabled(true)
                                        .gcp(
                                            SandboxResponse.ProxyConfig.Rule.Gcp.builder()
                                                .addScope("string")
                                                .serviceAccountJson(
                                                    SandboxResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            SandboxResponse.ProxyConfig.Rule.Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            SandboxResponse.ProxyConfig.Rule.Header.builder()
                                                .name("name")
                                                .type(
                                                    SandboxResponse.ProxyConfig.Rule.Header.Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchHost("string")
                                        .addMatchPath("string")
                                        .type("type")
                                        .build()
                                )
                                .build()
                        )
                        .sizeClass("size_class")
                        .snapshotId("snapshot_id")
                        .status("status")
                        .statusMessage("status_message")
                        .stoppedAt("stopped_at")
                        .updatedAt("updated_at")
                        .updatedBy("updated_by")
                        .vcpus(0L)
                        .build()
                )
                .build()

        val roundtrippedSandboxListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(sandboxListResponse),
                jacksonTypeRef<SandboxListResponse>(),
            )

        assertThat(roundtrippedSandboxListResponse).isEqualTo(sandboxListResponse)
    }
}
