// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.charts

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.JsonValue
import com.langchain.smith.core.jsonMapper
import com.langchain.smith.models.sessions.CustomChartsSection
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomChartsResponseTest {

    @Test
    fun create() {
        val customChartsResponse =
            CustomChartsResponse.builder()
                .addSection(
                    CustomChartsSection.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addChart(
                            SingleCustomChartResponse.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .chartType(CustomChartType.LINE)
                                .addData(
                                    CustomChartsDataPoint.builder()
                                        .seriesId("series_id")
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .value(0.0)
                                        .group("group")
                                        .build()
                                )
                                .index(0L)
                                .addSeries(
                                    CustomChartSeries.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .metric(CustomChartMetric.RUN_COUNT)
                                        .name("name")
                                        .feedbackKey("feedback_key")
                                        .filters(
                                            CustomChartSeriesFilters.builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .groupBy(
                                            CustomChartSeries.GroupBy.builder()
                                                .attribute(CustomChartSeries.GroupBy.Attribute.NAME)
                                                .maxGroups(0L)
                                                .path("path")
                                                .setBy(CustomChartSeries.GroupBy.SetBy.SECTION)
                                                .build()
                                        )
                                        .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .title("title")
                                .commonFilters(
                                    CustomChartSeriesFilters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .description("description")
                                .metadata(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .title("title")
                        .description("description")
                        .index(0L)
                        .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addSubSection(
                            CustomChartsSection.SubSection.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addChart(
                                    SingleCustomChartResponse.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .chartType(CustomChartType.LINE)
                                        .addData(
                                            CustomChartsDataPoint.builder()
                                                .seriesId("series_id")
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .value(0.0)
                                                .group("group")
                                                .build()
                                        )
                                        .index(0L)
                                        .addSeries(
                                            CustomChartSeries.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .metric(CustomChartMetric.RUN_COUNT)
                                                .name("name")
                                                .feedbackKey("feedback_key")
                                                .filters(
                                                    CustomChartSeriesFilters.builder()
                                                        .filter("filter")
                                                        .addSession(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .traceFilter("trace_filter")
                                                        .treeFilter("tree_filter")
                                                        .build()
                                                )
                                                .groupBy(
                                                    CustomChartSeries.GroupBy.builder()
                                                        .attribute(
                                                            CustomChartSeries.GroupBy.Attribute.NAME
                                                        )
                                                        .maxGroups(0L)
                                                        .path("path")
                                                        .setBy(
                                                            CustomChartSeries.GroupBy.SetBy.SECTION
                                                        )
                                                        .build()
                                                )
                                                .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .title("title")
                                        .commonFilters(
                                            CustomChartSeriesFilters.builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .description("description")
                                        .metadata(JsonValue.from(mapOf<String, Any>()))
                                        .build()
                                )
                                .index(0L)
                                .title("title")
                                .description("description")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(customChartsResponse.sections())
            .containsExactly(
                CustomChartsSection.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addChart(
                        SingleCustomChartResponse.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .chartType(CustomChartType.LINE)
                            .addData(
                                CustomChartsDataPoint.builder()
                                    .seriesId("series_id")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .value(0.0)
                                    .group("group")
                                    .build()
                            )
                            .index(0L)
                            .addSeries(
                                CustomChartSeries.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .metric(CustomChartMetric.RUN_COUNT)
                                    .name("name")
                                    .feedbackKey("feedback_key")
                                    .filters(
                                        CustomChartSeriesFilters.builder()
                                            .filter("filter")
                                            .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .traceFilter("trace_filter")
                                            .treeFilter("tree_filter")
                                            .build()
                                    )
                                    .groupBy(
                                        CustomChartSeries.GroupBy.builder()
                                            .attribute(CustomChartSeries.GroupBy.Attribute.NAME)
                                            .maxGroups(0L)
                                            .path("path")
                                            .setBy(CustomChartSeries.GroupBy.SetBy.SECTION)
                                            .build()
                                    )
                                    .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .title("title")
                            .commonFilters(
                                CustomChartSeriesFilters.builder()
                                    .filter("filter")
                                    .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .traceFilter("trace_filter")
                                    .treeFilter("tree_filter")
                                    .build()
                            )
                            .description("description")
                            .metadata(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .title("title")
                    .description("description")
                    .index(0L)
                    .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addSubSection(
                        CustomChartsSection.SubSection.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addChart(
                                SingleCustomChartResponse.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .chartType(CustomChartType.LINE)
                                    .addData(
                                        CustomChartsDataPoint.builder()
                                            .seriesId("series_id")
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .value(0.0)
                                            .group("group")
                                            .build()
                                    )
                                    .index(0L)
                                    .addSeries(
                                        CustomChartSeries.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .metric(CustomChartMetric.RUN_COUNT)
                                            .name("name")
                                            .feedbackKey("feedback_key")
                                            .filters(
                                                CustomChartSeriesFilters.builder()
                                                    .filter("filter")
                                                    .addSession(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .traceFilter("trace_filter")
                                                    .treeFilter("tree_filter")
                                                    .build()
                                            )
                                            .groupBy(
                                                CustomChartSeries.GroupBy.builder()
                                                    .attribute(
                                                        CustomChartSeries.GroupBy.Attribute.NAME
                                                    )
                                                    .maxGroups(0L)
                                                    .path("path")
                                                    .setBy(CustomChartSeries.GroupBy.SetBy.SECTION)
                                                    .build()
                                            )
                                            .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                            .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .title("title")
                                    .commonFilters(
                                        CustomChartSeriesFilters.builder()
                                            .filter("filter")
                                            .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .traceFilter("trace_filter")
                                            .treeFilter("tree_filter")
                                            .build()
                                    )
                                    .description("description")
                                    .metadata(JsonValue.from(mapOf<String, Any>()))
                                    .build()
                            )
                            .index(0L)
                            .title("title")
                            .description("description")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customChartsResponse =
            CustomChartsResponse.builder()
                .addSection(
                    CustomChartsSection.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addChart(
                            SingleCustomChartResponse.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .chartType(CustomChartType.LINE)
                                .addData(
                                    CustomChartsDataPoint.builder()
                                        .seriesId("series_id")
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .value(0.0)
                                        .group("group")
                                        .build()
                                )
                                .index(0L)
                                .addSeries(
                                    CustomChartSeries.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .metric(CustomChartMetric.RUN_COUNT)
                                        .name("name")
                                        .feedbackKey("feedback_key")
                                        .filters(
                                            CustomChartSeriesFilters.builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .groupBy(
                                            CustomChartSeries.GroupBy.builder()
                                                .attribute(CustomChartSeries.GroupBy.Attribute.NAME)
                                                .maxGroups(0L)
                                                .path("path")
                                                .setBy(CustomChartSeries.GroupBy.SetBy.SECTION)
                                                .build()
                                        )
                                        .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .title("title")
                                .commonFilters(
                                    CustomChartSeriesFilters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .description("description")
                                .metadata(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .title("title")
                        .description("description")
                        .index(0L)
                        .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addSubSection(
                            CustomChartsSection.SubSection.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addChart(
                                    SingleCustomChartResponse.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .chartType(CustomChartType.LINE)
                                        .addData(
                                            CustomChartsDataPoint.builder()
                                                .seriesId("series_id")
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .value(0.0)
                                                .group("group")
                                                .build()
                                        )
                                        .index(0L)
                                        .addSeries(
                                            CustomChartSeries.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .metric(CustomChartMetric.RUN_COUNT)
                                                .name("name")
                                                .feedbackKey("feedback_key")
                                                .filters(
                                                    CustomChartSeriesFilters.builder()
                                                        .filter("filter")
                                                        .addSession(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .traceFilter("trace_filter")
                                                        .treeFilter("tree_filter")
                                                        .build()
                                                )
                                                .groupBy(
                                                    CustomChartSeries.GroupBy.builder()
                                                        .attribute(
                                                            CustomChartSeries.GroupBy.Attribute.NAME
                                                        )
                                                        .maxGroups(0L)
                                                        .path("path")
                                                        .setBy(
                                                            CustomChartSeries.GroupBy.SetBy.SECTION
                                                        )
                                                        .build()
                                                )
                                                .projectMetric(HostProjectChartMetric.MEMORY_USAGE)
                                                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .title("title")
                                        .commonFilters(
                                            CustomChartSeriesFilters.builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .description("description")
                                        .metadata(JsonValue.from(mapOf<String, Any>()))
                                        .build()
                                )
                                .index(0L)
                                .title("title")
                                .description("description")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedCustomChartsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customChartsResponse),
                jacksonTypeRef<CustomChartsResponse>(),
            )

        assertThat(roundtrippedCustomChartsResponse).isEqualTo(customChartsResponse)
    }
}
