// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.langchain.smith.core.JsonValue
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxCreateParamsTest {

    @Test
    fun create() {
        BoxCreateParams.builder()
            .cpuMillicores(0L)
            .deleteAfterStopSeconds(0L)
            .envVars(
                BoxCreateParams.EnvVars.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
            .fsCapacityBytes(0L)
            .idleTtlSeconds(0L)
            .memBytes(0L)
            .mountConfig(
                BoxCreateParams.MountConfig.builder()
                    .auth(
                        BoxCreateParams.MountConfig.Auth.builder()
                            .aws(
                                BoxCreateParams.MountConfig.Auth.Aws.builder()
                                    .accessKeyId(
                                        BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxCreateParams.MountConfig.Auth.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .gcp(
                                BoxCreateParams.MountConfig.Auth.Gcp.builder()
                                    .serviceAccountJson(
                                        BoxCreateParams.MountConfig.Auth.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addMount(
                        BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.builder()
                            .id("id")
                            .mountPath("mount_path")
                            .s3(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.S3
                                    .builder()
                                    .bucket("bucket")
                                    .region("region")
                                    .endpointUrl("endpoint_url")
                                    .pathStyle(true)
                                    .prefix("prefix")
                                    .build()
                            )
                            .type(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Type
                                    .S3
                            )
                            .cache(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Cache
                                    .builder()
                                    .maxSizeBytes(0L)
                                    .writebackSeconds(0L)
                                    .build()
                            )
                            .gcs(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Gcs
                                    .builder()
                                    .bucket("bucket")
                                    .prefix("prefix")
                                    .build()
                            )
                            .git(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Git
                                    .builder()
                                    .remoteUrl("remote_url")
                                    .ref(
                                        BoxCreateParams.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Git
                                            .Ref
                                            .builder()
                                            .name("name")
                                            .type(
                                                BoxCreateParams.MountConfig.Mount
                                                    .SandboxapiS3BucketMountSpec
                                                    .Git
                                                    .Ref
                                                    .Type
                                                    .BRANCH
                                            )
                                            .build()
                                    )
                                    .refreshIntervalSeconds(1L)
                                    .build()
                            )
                            .readOnly(true)
                            .build()
                    )
                    .build()
            )
            .name("name")
            .proxyConfig(
                BoxCreateParams.ProxyConfig.builder()
                    .accessControl(
                        BoxCreateParams.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxCreateParams.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxCreateParams.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxCreateParams.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxCreateParams.ProxyConfig.Rule.builder()
                            .name("name")
                            .aws(
                                BoxCreateParams.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxCreateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .gcp(
                                BoxCreateParams.ProxyConfig.Rule.Gcp.builder()
                                    .addScope("string")
                                    .serviceAccountJson(
                                        BoxCreateParams.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addHeader(
                                BoxCreateParams.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(BoxCreateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
            .restoreMemory(true)
            .snapshotId("snapshot_id")
            .snapshotName("snapshot_name")
            .addTagValueId("string")
            .vcpus(0L)
            .build()
    }

    @Test
    fun body() {
        val params =
            BoxCreateParams.builder()
                .cpuMillicores(0L)
                .deleteAfterStopSeconds(0L)
                .envVars(
                    BoxCreateParams.EnvVars.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .mountConfig(
                    BoxCreateParams.MountConfig.builder()
                        .auth(
                            BoxCreateParams.MountConfig.Auth.builder()
                                .aws(
                                    BoxCreateParams.MountConfig.Auth.Aws.builder()
                                        .accessKeyId(
                                            BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxCreateParams.MountConfig.Auth.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxCreateParams.MountConfig.Auth.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .gcp(
                                    BoxCreateParams.MountConfig.Auth.Gcp.builder()
                                        .serviceAccountJson(
                                            BoxCreateParams.MountConfig.Auth.Gcp.ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxCreateParams.MountConfig.Auth.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addMount(
                            BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.builder()
                                .id("id")
                                .mountPath("mount_path")
                                .s3(
                                    BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.S3
                                        .builder()
                                        .bucket("bucket")
                                        .region("region")
                                        .endpointUrl("endpoint_url")
                                        .pathStyle(true)
                                        .prefix("prefix")
                                        .build()
                                )
                                .type(
                                    BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .Type
                                        .S3
                                )
                                .cache(
                                    BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .Cache
                                        .builder()
                                        .maxSizeBytes(0L)
                                        .writebackSeconds(0L)
                                        .build()
                                )
                                .gcs(
                                    BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .Gcs
                                        .builder()
                                        .bucket("bucket")
                                        .prefix("prefix")
                                        .build()
                                )
                                .git(
                                    BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                        .Git
                                        .builder()
                                        .remoteUrl("remote_url")
                                        .ref(
                                            BoxCreateParams.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Git
                                                .Ref
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxCreateParams.MountConfig.Mount
                                                        .SandboxapiS3BucketMountSpec
                                                        .Git
                                                        .Ref
                                                        .Type
                                                        .BRANCH
                                                )
                                                .build()
                                        )
                                        .refreshIntervalSeconds(1L)
                                        .build()
                                )
                                .readOnly(true)
                                .build()
                        )
                        .build()
                )
                .name("name")
                .proxyConfig(
                    BoxCreateParams.ProxyConfig.builder()
                        .accessControl(
                            BoxCreateParams.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxCreateParams.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxCreateParams.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxCreateParams.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxCreateParams.ProxyConfig.Rule.builder()
                                .name("name")
                                .aws(
                                    BoxCreateParams.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxCreateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxCreateParams.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .gcp(
                                    BoxCreateParams.ProxyConfig.Rule.Gcp.builder()
                                        .addScope("string")
                                        .serviceAccountJson(
                                            BoxCreateParams.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxCreateParams.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addHeader(
                                    BoxCreateParams.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxCreateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .restoreMemory(true)
                .snapshotId("snapshot_id")
                .snapshotName("snapshot_name")
                .addTagValueId("string")
                .vcpus(0L)
                .build()

        val body = params._body()

        assertThat(body.cpuMillicores()).contains(0L)
        assertThat(body.deleteAfterStopSeconds()).contains(0L)
        assertThat(body.envVars())
            .contains(
                BoxCreateParams.EnvVars.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(body.fsCapacityBytes()).contains(0L)
        assertThat(body.idleTtlSeconds()).contains(0L)
        assertThat(body.memBytes()).contains(0L)
        assertThat(body.mountConfig())
            .contains(
                BoxCreateParams.MountConfig.builder()
                    .auth(
                        BoxCreateParams.MountConfig.Auth.builder()
                            .aws(
                                BoxCreateParams.MountConfig.Auth.Aws.builder()
                                    .accessKeyId(
                                        BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxCreateParams.MountConfig.Auth.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .gcp(
                                BoxCreateParams.MountConfig.Auth.Gcp.builder()
                                    .serviceAccountJson(
                                        BoxCreateParams.MountConfig.Auth.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxCreateParams.MountConfig.Auth.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addMount(
                        BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.builder()
                            .id("id")
                            .mountPath("mount_path")
                            .s3(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.S3
                                    .builder()
                                    .bucket("bucket")
                                    .region("region")
                                    .endpointUrl("endpoint_url")
                                    .pathStyle(true)
                                    .prefix("prefix")
                                    .build()
                            )
                            .type(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Type
                                    .S3
                            )
                            .cache(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Cache
                                    .builder()
                                    .maxSizeBytes(0L)
                                    .writebackSeconds(0L)
                                    .build()
                            )
                            .gcs(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Gcs
                                    .builder()
                                    .bucket("bucket")
                                    .prefix("prefix")
                                    .build()
                            )
                            .git(
                                BoxCreateParams.MountConfig.Mount.SandboxapiS3BucketMountSpec.Git
                                    .builder()
                                    .remoteUrl("remote_url")
                                    .ref(
                                        BoxCreateParams.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Git
                                            .Ref
                                            .builder()
                                            .name("name")
                                            .type(
                                                BoxCreateParams.MountConfig.Mount
                                                    .SandboxapiS3BucketMountSpec
                                                    .Git
                                                    .Ref
                                                    .Type
                                                    .BRANCH
                                            )
                                            .build()
                                    )
                                    .refreshIntervalSeconds(1L)
                                    .build()
                            )
                            .readOnly(true)
                            .build()
                    )
                    .build()
            )
        assertThat(body.name()).contains("name")
        assertThat(body.proxyConfig())
            .contains(
                BoxCreateParams.ProxyConfig.builder()
                    .accessControl(
                        BoxCreateParams.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxCreateParams.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxCreateParams.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxCreateParams.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxCreateParams.ProxyConfig.Rule.builder()
                            .name("name")
                            .aws(
                                BoxCreateParams.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxCreateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .gcp(
                                BoxCreateParams.ProxyConfig.Rule.Gcp.builder()
                                    .addScope("string")
                                    .serviceAccountJson(
                                        BoxCreateParams.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxCreateParams.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addHeader(
                                BoxCreateParams.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(BoxCreateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
        assertThat(body.restoreMemory()).contains(true)
        assertThat(body.snapshotId()).contains("snapshot_id")
        assertThat(body.snapshotName()).contains("snapshot_name")
        assertThat(body.tagValueIds().getOrNull()).containsExactly("string")
        assertThat(body.vcpus()).contains(0L)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = BoxCreateParams.builder().build()

        val body = params._body()

        assertThat(body.snapshotId()).isEmpty()
        assertThat(body.snapshotName()).isEmpty()
    }
}
