// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxListResponseTest {

    @Test
    fun create() {
        val boxListResponse =
            BoxListResponse.builder()
                .offset(0L)
                .addSandbox(
                    BoxListResponse.Sandbox.builder()
                        .id("id")
                        .createdAt("created_at")
                        .createdBy("created_by")
                        .dataplaneUrl("dataplane_url")
                        .deleteAfterStopSeconds(0L)
                        .fsCapacityBytes(0L)
                        .idleTtlSeconds(0L)
                        .memBytes(0L)
                        .addMount(
                            BoxListResponse.Sandbox.Mount.builder()
                                .id("id")
                                .mountPath("mount_path")
                                .s3(
                                    BoxListResponse.Sandbox.Mount.S3.builder()
                                        .bucket("bucket")
                                        .endpointUrl("endpoint_url")
                                        .region("region")
                                        .pathStyle(true)
                                        .prefix("prefix")
                                        .build()
                                )
                                .type(BoxListResponse.Sandbox.Mount.Type.S3)
                                .cache(
                                    BoxListResponse.Sandbox.Mount.Cache.builder()
                                        .maxSizeBytes(0L)
                                        .writebackSeconds(0L)
                                        .build()
                                )
                                .readOnly(true)
                                .build()
                        )
                        .name("name")
                        .proxyConfig(
                            BoxListResponse.Sandbox.ProxyConfig.builder()
                                .accessControl(
                                    BoxListResponse.Sandbox.ProxyConfig.AccessControl.builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    BoxListResponse.Sandbox.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .fullRequest(true)
                                        .addRequestHeader(
                                            BoxListResponse.Sandbox.ProxyConfig.Callback
                                                .RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxListResponse.Sandbox.ProxyConfig.Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    BoxListResponse.Sandbox.ProxyConfig.Rule.builder()
                                        .name("name")
                                        .aws(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Aws.builder()
                                                .accessKeyId(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .enabled(true)
                                        .gcp(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp.builder()
                                                .addScope("string")
                                                .serviceAccountJson(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Header
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Header
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchHost("string")
                                        .addMatchPath("string")
                                        .type("type")
                                        .build()
                                )
                                .build()
                        )
                        .sizeClass("size_class")
                        .snapshotId("snapshot_id")
                        .status("status")
                        .statusMessage("status_message")
                        .stoppedAt("stopped_at")
                        .updatedAt("updated_at")
                        .updatedBy("updated_by")
                        .vcpus(0L)
                        .build()
                )
                .build()

        assertThat(boxListResponse.offset()).contains(0L)
        assertThat(boxListResponse.sandboxes().getOrNull())
            .containsExactly(
                BoxListResponse.Sandbox.builder()
                    .id("id")
                    .createdAt("created_at")
                    .createdBy("created_by")
                    .dataplaneUrl("dataplane_url")
                    .deleteAfterStopSeconds(0L)
                    .fsCapacityBytes(0L)
                    .idleTtlSeconds(0L)
                    .memBytes(0L)
                    .addMount(
                        BoxListResponse.Sandbox.Mount.builder()
                            .id("id")
                            .mountPath("mount_path")
                            .s3(
                                BoxListResponse.Sandbox.Mount.S3.builder()
                                    .bucket("bucket")
                                    .endpointUrl("endpoint_url")
                                    .region("region")
                                    .pathStyle(true)
                                    .prefix("prefix")
                                    .build()
                            )
                            .type(BoxListResponse.Sandbox.Mount.Type.S3)
                            .cache(
                                BoxListResponse.Sandbox.Mount.Cache.builder()
                                    .maxSizeBytes(0L)
                                    .writebackSeconds(0L)
                                    .build()
                            )
                            .readOnly(true)
                            .build()
                    )
                    .name("name")
                    .proxyConfig(
                        BoxListResponse.Sandbox.ProxyConfig.builder()
                            .accessControl(
                                BoxListResponse.Sandbox.ProxyConfig.AccessControl.builder()
                                    .addAllowList("string")
                                    .addDenyList("string")
                                    .build()
                            )
                            .addCallback(
                                BoxListResponse.Sandbox.ProxyConfig.Callback.builder()
                                    .addMatchHost("string")
                                    .ttlSeconds(60L)
                                    .url("url")
                                    .fullRequest(true)
                                    .addRequestHeader(
                                        BoxListResponse.Sandbox.ProxyConfig.Callback.RequestHeader
                                            .builder()
                                            .name("name")
                                            .type(
                                                BoxListResponse.Sandbox.ProxyConfig.Callback
                                                    .RequestHeader
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addNoProxy("string")
                            .addRule(
                                BoxListResponse.Sandbox.ProxyConfig.Rule.builder()
                                    .name("name")
                                    .aws(
                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Aws.builder()
                                            .accessKeyId(
                                                BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                    .AccessKeyId
                                                    .builder()
                                                    .type(
                                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                            .AccessKeyId
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .secretAccessKey(
                                                BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                    .SecretAccessKey
                                                    .builder()
                                                    .type(
                                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                            .SecretAccessKey
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .enabled(true)
                                    .gcp(
                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp.builder()
                                            .addScope("string")
                                            .serviceAccountJson(
                                                BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .builder()
                                                    .type(
                                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp
                                                            .ServiceAccountJson
                                                            .Type
                                                            .PLAINTEXT
                                                    )
                                                    .isSet(true)
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addHeader(
                                        BoxListResponse.Sandbox.ProxyConfig.Rule.Header.builder()
                                            .name("name")
                                            .type(
                                                BoxListResponse.Sandbox.ProxyConfig.Rule.Header.Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .addMatchHost("string")
                                    .addMatchPath("string")
                                    .type("type")
                                    .build()
                            )
                            .build()
                    )
                    .sizeClass("size_class")
                    .snapshotId("snapshot_id")
                    .status("status")
                    .statusMessage("status_message")
                    .stoppedAt("stopped_at")
                    .updatedAt("updated_at")
                    .updatedBy("updated_by")
                    .vcpus(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val boxListResponse =
            BoxListResponse.builder()
                .offset(0L)
                .addSandbox(
                    BoxListResponse.Sandbox.builder()
                        .id("id")
                        .createdAt("created_at")
                        .createdBy("created_by")
                        .dataplaneUrl("dataplane_url")
                        .deleteAfterStopSeconds(0L)
                        .fsCapacityBytes(0L)
                        .idleTtlSeconds(0L)
                        .memBytes(0L)
                        .addMount(
                            BoxListResponse.Sandbox.Mount.builder()
                                .id("id")
                                .mountPath("mount_path")
                                .s3(
                                    BoxListResponse.Sandbox.Mount.S3.builder()
                                        .bucket("bucket")
                                        .endpointUrl("endpoint_url")
                                        .region("region")
                                        .pathStyle(true)
                                        .prefix("prefix")
                                        .build()
                                )
                                .type(BoxListResponse.Sandbox.Mount.Type.S3)
                                .cache(
                                    BoxListResponse.Sandbox.Mount.Cache.builder()
                                        .maxSizeBytes(0L)
                                        .writebackSeconds(0L)
                                        .build()
                                )
                                .readOnly(true)
                                .build()
                        )
                        .name("name")
                        .proxyConfig(
                            BoxListResponse.Sandbox.ProxyConfig.builder()
                                .accessControl(
                                    BoxListResponse.Sandbox.ProxyConfig.AccessControl.builder()
                                        .addAllowList("string")
                                        .addDenyList("string")
                                        .build()
                                )
                                .addCallback(
                                    BoxListResponse.Sandbox.ProxyConfig.Callback.builder()
                                        .addMatchHost("string")
                                        .ttlSeconds(60L)
                                        .url("url")
                                        .fullRequest(true)
                                        .addRequestHeader(
                                            BoxListResponse.Sandbox.ProxyConfig.Callback
                                                .RequestHeader
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxListResponse.Sandbox.ProxyConfig.Callback
                                                        .RequestHeader
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addNoProxy("string")
                                .addRule(
                                    BoxListResponse.Sandbox.ProxyConfig.Rule.builder()
                                        .name("name")
                                        .aws(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Aws.builder()
                                                .accessKeyId(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Aws
                                                                .AccessKeyId
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .secretAccessKey(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Aws
                                                                .SecretAccessKey
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .enabled(true)
                                        .gcp(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp.builder()
                                                .addScope("string")
                                                .serviceAccountJson(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .builder()
                                                        .type(
                                                            BoxListResponse.Sandbox.ProxyConfig.Rule
                                                                .Gcp
                                                                .ServiceAccountJson
                                                                .Type
                                                                .PLAINTEXT
                                                        )
                                                        .isSet(true)
                                                        .value("value")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            BoxListResponse.Sandbox.ProxyConfig.Rule.Header
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxListResponse.Sandbox.ProxyConfig.Rule.Header
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .addMatchHost("string")
                                        .addMatchPath("string")
                                        .type("type")
                                        .build()
                                )
                                .build()
                        )
                        .sizeClass("size_class")
                        .snapshotId("snapshot_id")
                        .status("status")
                        .statusMessage("status_message")
                        .stoppedAt("stopped_at")
                        .updatedAt("updated_at")
                        .updatedBy("updated_by")
                        .vcpus(0L)
                        .build()
                )
                .build()

        val roundtrippedBoxListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(boxListResponse),
                jacksonTypeRef<BoxListResponse>(),
            )

        assertThat(roundtrippedBoxListResponse).isEqualTo(boxListResponse)
    }
}
