// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxRetrieveResponseTest {

    @Test
    fun create() {
        val boxRetrieveResponse =
            BoxRetrieveResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .expiresAt("expires_at")
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .name("name")
                .proxyConfig(
                    BoxRetrieveResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxRetrieveResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .addRequestHeader(
                                    BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader
                                                .Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxRetrieveResponse.ProxyConfig.Rule.builder()
                                .addMatchHost("string")
                                .name("name")
                                .enabled(true)
                                .addHeader(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Header.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchPath("string")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .ttlSeconds(0L)
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        assertThat(boxRetrieveResponse.id()).contains("id")
        assertThat(boxRetrieveResponse.createdAt()).contains("created_at")
        assertThat(boxRetrieveResponse.createdBy()).contains("created_by")
        assertThat(boxRetrieveResponse.dataplaneUrl()).contains("dataplane_url")
        assertThat(boxRetrieveResponse.expiresAt()).contains("expires_at")
        assertThat(boxRetrieveResponse.fsCapacityBytes()).contains(0L)
        assertThat(boxRetrieveResponse.idleTtlSeconds()).contains(0L)
        assertThat(boxRetrieveResponse.memBytes()).contains(0L)
        assertThat(boxRetrieveResponse.name()).contains("name")
        assertThat(boxRetrieveResponse.proxyConfig())
            .contains(
                BoxRetrieveResponse.ProxyConfig.builder()
                    .accessControl(
                        BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxRetrieveResponse.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .addRequestHeader(
                                BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxRetrieveResponse.ProxyConfig.Rule.builder()
                            .addMatchHost("string")
                            .name("name")
                            .enabled(true)
                            .addHeader(
                                BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(
                                        BoxRetrieveResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchPath("string")
                            .build()
                    )
                    .build()
            )
        assertThat(boxRetrieveResponse.sizeClass()).contains("size_class")
        assertThat(boxRetrieveResponse.snapshotId()).contains("snapshot_id")
        assertThat(boxRetrieveResponse.status()).contains("status")
        assertThat(boxRetrieveResponse.statusMessage()).contains("status_message")
        assertThat(boxRetrieveResponse.ttlSeconds()).contains(0L)
        assertThat(boxRetrieveResponse.updatedAt()).contains("updated_at")
        assertThat(boxRetrieveResponse.updatedBy()).contains("updated_by")
        assertThat(boxRetrieveResponse.vcpus()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val boxRetrieveResponse =
            BoxRetrieveResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .expiresAt("expires_at")
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .name("name")
                .proxyConfig(
                    BoxRetrieveResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxRetrieveResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .addRequestHeader(
                                    BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader
                                                .Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxRetrieveResponse.ProxyConfig.Rule.builder()
                                .addMatchHost("string")
                                .name("name")
                                .enabled(true)
                                .addHeader(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Header.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchPath("string")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .ttlSeconds(0L)
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        val roundtrippedBoxRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(boxRetrieveResponse),
                jacksonTypeRef<BoxRetrieveResponse>(),
            )

        assertThat(roundtrippedBoxRetrieveResponse).isEqualTo(boxRetrieveResponse)
    }
}
