// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxRetrieveResponseTest {

    @Test
    fun create() {
        val boxRetrieveResponse =
            BoxRetrieveResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .mountConfig(
                    BoxRetrieveResponse.MountConfig.builder()
                        .auth(
                            BoxRetrieveResponse.MountConfig.Auth.builder()
                                .aws(
                                    BoxRetrieveResponse.MountConfig.Auth.Aws.builder()
                                        .accessKeyId(
                                            BoxRetrieveResponse.MountConfig.Auth.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxRetrieveResponse.MountConfig.Auth.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .gcp(
                                    BoxRetrieveResponse.MountConfig.Auth.Gcp.builder()
                                        .serviceAccountJson(
                                            BoxRetrieveResponse.MountConfig.Auth.Gcp
                                                .ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addMount(
                            BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                .builder()
                                .id("id")
                                .mountPath("mount_path")
                                .s3(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .S3
                                        .builder()
                                        .bucket("bucket")
                                        .region("region")
                                        .endpointUrl("endpoint_url")
                                        .pathStyle(true)
                                        .prefix("prefix")
                                        .build()
                                )
                                .type(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Type
                                        .S3
                                )
                                .cache(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Cache
                                        .builder()
                                        .maxSizeBytes(0L)
                                        .writebackSeconds(0L)
                                        .build()
                                )
                                .gcs(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Gcs
                                        .builder()
                                        .bucket("bucket")
                                        .prefix("prefix")
                                        .build()
                                )
                                .git(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Git
                                        .builder()
                                        .remoteUrl("remote_url")
                                        .ref(
                                            BoxRetrieveResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Git
                                                .Ref
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Mount
                                                        .SandboxapiS3BucketMountSpec
                                                        .Git
                                                        .Ref
                                                        .Type
                                                        .BRANCH
                                                )
                                                .build()
                                        )
                                        .refreshIntervalSeconds(1L)
                                        .build()
                                )
                                .readOnly(true)
                                .build()
                        )
                        .build()
                )
                .name("name")
                .proxyConfig(
                    BoxRetrieveResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxRetrieveResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader
                                                .Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxRetrieveResponse.ProxyConfig.Rule.builder()
                                .name("name")
                                .aws(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .gcp(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Gcp.builder()
                                        .addScope("string")
                                        .serviceAccountJson(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Gcp
                                                .ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addHeader(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Header.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        assertThat(boxRetrieveResponse.id()).contains("id")
        assertThat(boxRetrieveResponse.createdAt()).contains("created_at")
        assertThat(boxRetrieveResponse.createdBy()).contains("created_by")
        assertThat(boxRetrieveResponse.dataplaneUrl()).contains("dataplane_url")
        assertThat(boxRetrieveResponse.deleteAfterStopSeconds()).contains(0L)
        assertThat(boxRetrieveResponse.fsCapacityBytes()).contains(0L)
        assertThat(boxRetrieveResponse.idleTtlSeconds()).contains(0L)
        assertThat(boxRetrieveResponse.memBytes()).contains(0L)
        assertThat(boxRetrieveResponse.mountConfig())
            .contains(
                BoxRetrieveResponse.MountConfig.builder()
                    .auth(
                        BoxRetrieveResponse.MountConfig.Auth.builder()
                            .aws(
                                BoxRetrieveResponse.MountConfig.Auth.Aws.builder()
                                    .accessKeyId(
                                        BoxRetrieveResponse.MountConfig.Auth.Aws.AccessKeyId
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.MountConfig.Auth.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxRetrieveResponse.MountConfig.Auth.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.MountConfig.Auth.Aws
                                                    .SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .gcp(
                                BoxRetrieveResponse.MountConfig.Auth.Gcp.builder()
                                    .serviceAccountJson(
                                        BoxRetrieveResponse.MountConfig.Auth.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.MountConfig.Auth.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addMount(
                        BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec.builder()
                            .id("id")
                            .mountPath("mount_path")
                            .s3(
                                BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec.S3
                                    .builder()
                                    .bucket("bucket")
                                    .region("region")
                                    .endpointUrl("endpoint_url")
                                    .pathStyle(true)
                                    .prefix("prefix")
                                    .build()
                            )
                            .type(
                                BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                    .Type
                                    .S3
                            )
                            .cache(
                                BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                    .Cache
                                    .builder()
                                    .maxSizeBytes(0L)
                                    .writebackSeconds(0L)
                                    .build()
                            )
                            .gcs(
                                BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                    .Gcs
                                    .builder()
                                    .bucket("bucket")
                                    .prefix("prefix")
                                    .build()
                            )
                            .git(
                                BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                    .Git
                                    .builder()
                                    .remoteUrl("remote_url")
                                    .ref(
                                        BoxRetrieveResponse.MountConfig.Mount
                                            .SandboxapiS3BucketMountSpec
                                            .Git
                                            .Ref
                                            .builder()
                                            .name("name")
                                            .type(
                                                BoxRetrieveResponse.MountConfig.Mount
                                                    .SandboxapiS3BucketMountSpec
                                                    .Git
                                                    .Ref
                                                    .Type
                                                    .BRANCH
                                            )
                                            .build()
                                    )
                                    .refreshIntervalSeconds(1L)
                                    .build()
                            )
                            .readOnly(true)
                            .build()
                    )
                    .build()
            )
        assertThat(boxRetrieveResponse.name()).contains("name")
        assertThat(boxRetrieveResponse.proxyConfig())
            .contains(
                BoxRetrieveResponse.ProxyConfig.builder()
                    .accessControl(
                        BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxRetrieveResponse.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxRetrieveResponse.ProxyConfig.Rule.builder()
                            .name("name")
                            .aws(
                                BoxRetrieveResponse.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxRetrieveResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxRetrieveResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.ProxyConfig.Rule.Aws
                                                    .SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .gcp(
                                BoxRetrieveResponse.ProxyConfig.Rule.Gcp.builder()
                                    .addScope("string")
                                    .serviceAccountJson(
                                        BoxRetrieveResponse.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxRetrieveResponse.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addHeader(
                                BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(
                                        BoxRetrieveResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
        assertThat(boxRetrieveResponse.sizeClass()).contains("size_class")
        assertThat(boxRetrieveResponse.snapshotId()).contains("snapshot_id")
        assertThat(boxRetrieveResponse.status()).contains("status")
        assertThat(boxRetrieveResponse.statusMessage()).contains("status_message")
        assertThat(boxRetrieveResponse.stoppedAt()).contains("stopped_at")
        assertThat(boxRetrieveResponse.updatedAt()).contains("updated_at")
        assertThat(boxRetrieveResponse.updatedBy()).contains("updated_by")
        assertThat(boxRetrieveResponse.vcpus()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val boxRetrieveResponse =
            BoxRetrieveResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .mountConfig(
                    BoxRetrieveResponse.MountConfig.builder()
                        .auth(
                            BoxRetrieveResponse.MountConfig.Auth.builder()
                                .aws(
                                    BoxRetrieveResponse.MountConfig.Auth.Aws.builder()
                                        .accessKeyId(
                                            BoxRetrieveResponse.MountConfig.Auth.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxRetrieveResponse.MountConfig.Auth.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .gcp(
                                    BoxRetrieveResponse.MountConfig.Auth.Gcp.builder()
                                        .serviceAccountJson(
                                            BoxRetrieveResponse.MountConfig.Auth.Gcp
                                                .ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Auth.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addMount(
                            BoxRetrieveResponse.MountConfig.Mount.SandboxapiS3BucketMountSpec
                                .builder()
                                .id("id")
                                .mountPath("mount_path")
                                .s3(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .S3
                                        .builder()
                                        .bucket("bucket")
                                        .region("region")
                                        .endpointUrl("endpoint_url")
                                        .pathStyle(true)
                                        .prefix("prefix")
                                        .build()
                                )
                                .type(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Type
                                        .S3
                                )
                                .cache(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Cache
                                        .builder()
                                        .maxSizeBytes(0L)
                                        .writebackSeconds(0L)
                                        .build()
                                )
                                .gcs(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Gcs
                                        .builder()
                                        .bucket("bucket")
                                        .prefix("prefix")
                                        .build()
                                )
                                .git(
                                    BoxRetrieveResponse.MountConfig.Mount
                                        .SandboxapiS3BucketMountSpec
                                        .Git
                                        .builder()
                                        .remoteUrl("remote_url")
                                        .ref(
                                            BoxRetrieveResponse.MountConfig.Mount
                                                .SandboxapiS3BucketMountSpec
                                                .Git
                                                .Ref
                                                .builder()
                                                .name("name")
                                                .type(
                                                    BoxRetrieveResponse.MountConfig.Mount
                                                        .SandboxapiS3BucketMountSpec
                                                        .Git
                                                        .Ref
                                                        .Type
                                                        .BRANCH
                                                )
                                                .build()
                                        )
                                        .refreshIntervalSeconds(1L)
                                        .build()
                                )
                                .readOnly(true)
                                .build()
                        )
                        .build()
                )
                .name("name")
                .proxyConfig(
                    BoxRetrieveResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxRetrieveResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxRetrieveResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Callback.RequestHeader
                                                .Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxRetrieveResponse.ProxyConfig.Rule.builder()
                                .name("name")
                                .aws(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .gcp(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Gcp.builder()
                                        .addScope("string")
                                        .serviceAccountJson(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Gcp
                                                .ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxRetrieveResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addHeader(
                                    BoxRetrieveResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxRetrieveResponse.ProxyConfig.Rule.Header.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        val roundtrippedBoxRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(boxRetrieveResponse),
                jacksonTypeRef<BoxRetrieveResponse>(),
            )

        assertThat(roundtrippedBoxRetrieveResponse).isEqualTo(boxRetrieveResponse)
    }
}
