// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxStartResponseTest {

    @Test
    fun create() {
        val boxStartResponse =
            BoxStartResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .addMount(
                    BoxStartResponse.Mount.builder()
                        .id("id")
                        .mountPath("mount_path")
                        .s3(
                            BoxStartResponse.Mount.S3.builder()
                                .bucket("bucket")
                                .endpointUrl("endpoint_url")
                                .region("region")
                                .pathStyle(true)
                                .prefix("prefix")
                                .build()
                        )
                        .type(BoxStartResponse.Mount.Type.S3)
                        .cache(
                            BoxStartResponse.Mount.Cache.builder()
                                .maxSizeBytes(0L)
                                .writebackSeconds(0L)
                                .build()
                        )
                        .readOnly(true)
                        .build()
                )
                .name("name")
                .proxyConfig(
                    BoxStartResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxStartResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxStartResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxStartResponse.ProxyConfig.Rule.builder()
                                .name("name")
                                .aws(
                                    BoxStartResponse.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxStartResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxStartResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .gcp(
                                    BoxStartResponse.ProxyConfig.Rule.Gcp.builder()
                                        .addScope("string")
                                        .serviceAccountJson(
                                            BoxStartResponse.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addHeader(
                                    BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        assertThat(boxStartResponse.id()).contains("id")
        assertThat(boxStartResponse.createdAt()).contains("created_at")
        assertThat(boxStartResponse.createdBy()).contains("created_by")
        assertThat(boxStartResponse.dataplaneUrl()).contains("dataplane_url")
        assertThat(boxStartResponse.deleteAfterStopSeconds()).contains(0L)
        assertThat(boxStartResponse.fsCapacityBytes()).contains(0L)
        assertThat(boxStartResponse.idleTtlSeconds()).contains(0L)
        assertThat(boxStartResponse.memBytes()).contains(0L)
        assertThat(boxStartResponse.mounts().getOrNull())
            .containsExactly(
                BoxStartResponse.Mount.builder()
                    .id("id")
                    .mountPath("mount_path")
                    .s3(
                        BoxStartResponse.Mount.S3.builder()
                            .bucket("bucket")
                            .endpointUrl("endpoint_url")
                            .region("region")
                            .pathStyle(true)
                            .prefix("prefix")
                            .build()
                    )
                    .type(BoxStartResponse.Mount.Type.S3)
                    .cache(
                        BoxStartResponse.Mount.Cache.builder()
                            .maxSizeBytes(0L)
                            .writebackSeconds(0L)
                            .build()
                    )
                    .readOnly(true)
                    .build()
            )
        assertThat(boxStartResponse.name()).contains("name")
        assertThat(boxStartResponse.proxyConfig())
            .contains(
                BoxStartResponse.ProxyConfig.builder()
                    .accessControl(
                        BoxStartResponse.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxStartResponse.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxStartResponse.ProxyConfig.Rule.builder()
                            .name("name")
                            .aws(
                                BoxStartResponse.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxStartResponse.ProxyConfig.Rule.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxStartResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxStartResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxStartResponse.ProxyConfig.Rule.Aws
                                                    .SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .gcp(
                                BoxStartResponse.ProxyConfig.Rule.Gcp.builder()
                                    .addScope("string")
                                    .serviceAccountJson(
                                        BoxStartResponse.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                            .builder()
                                            .type(
                                                BoxStartResponse.ProxyConfig.Rule.Gcp
                                                    .ServiceAccountJson
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .addHeader(
                                BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
        assertThat(boxStartResponse.sizeClass()).contains("size_class")
        assertThat(boxStartResponse.snapshotId()).contains("snapshot_id")
        assertThat(boxStartResponse.status()).contains("status")
        assertThat(boxStartResponse.statusMessage()).contains("status_message")
        assertThat(boxStartResponse.stoppedAt()).contains("stopped_at")
        assertThat(boxStartResponse.updatedAt()).contains("updated_at")
        assertThat(boxStartResponse.updatedBy()).contains("updated_by")
        assertThat(boxStartResponse.vcpus()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val boxStartResponse =
            BoxStartResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .addMount(
                    BoxStartResponse.Mount.builder()
                        .id("id")
                        .mountPath("mount_path")
                        .s3(
                            BoxStartResponse.Mount.S3.builder()
                                .bucket("bucket")
                                .endpointUrl("endpoint_url")
                                .region("region")
                                .pathStyle(true)
                                .prefix("prefix")
                                .build()
                        )
                        .type(BoxStartResponse.Mount.Type.S3)
                        .cache(
                            BoxStartResponse.Mount.Cache.builder()
                                .maxSizeBytes(0L)
                                .writebackSeconds(0L)
                                .build()
                        )
                        .readOnly(true)
                        .build()
                )
                .name("name")
                .proxyConfig(
                    BoxStartResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxStartResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxStartResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxStartResponse.ProxyConfig.Rule.builder()
                                .name("name")
                                .aws(
                                    BoxStartResponse.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxStartResponse.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Aws
                                                        .AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxStartResponse.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .gcp(
                                    BoxStartResponse.ProxyConfig.Rule.Gcp.builder()
                                        .addScope("string")
                                        .serviceAccountJson(
                                            BoxStartResponse.ProxyConfig.Rule.Gcp.ServiceAccountJson
                                                .builder()
                                                .type(
                                                    BoxStartResponse.ProxyConfig.Rule.Gcp
                                                        .ServiceAccountJson
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .addHeader(
                                    BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        val roundtrippedBoxStartResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(boxStartResponse),
                jacksonTypeRef<BoxStartResponse>(),
            )

        assertThat(roundtrippedBoxStartResponse).isEqualTo(boxStartResponse)
    }
}
