// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxStartResponseTest {

    @Test
    fun create() {
        val boxStartResponse =
            BoxStartResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .name("name")
                .proxyConfig(
                    BoxStartResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxStartResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxStartResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxStartResponse.ProxyConfig.Rule.builder()
                                .addMatchHost("string")
                                .name("name")
                                .enabled(true)
                                .addHeader(
                                    BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchPath("string")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        assertThat(boxStartResponse.id()).contains("id")
        assertThat(boxStartResponse.createdAt()).contains("created_at")
        assertThat(boxStartResponse.createdBy()).contains("created_by")
        assertThat(boxStartResponse.dataplaneUrl()).contains("dataplane_url")
        assertThat(boxStartResponse.deleteAfterStopSeconds()).contains(0L)
        assertThat(boxStartResponse.fsCapacityBytes()).contains(0L)
        assertThat(boxStartResponse.idleTtlSeconds()).contains(0L)
        assertThat(boxStartResponse.memBytes()).contains(0L)
        assertThat(boxStartResponse.name()).contains("name")
        assertThat(boxStartResponse.proxyConfig())
            .contains(
                BoxStartResponse.ProxyConfig.builder()
                    .accessControl(
                        BoxStartResponse.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxStartResponse.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                    .name("name")
                                    .type(
                                        BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxStartResponse.ProxyConfig.Rule.builder()
                            .addMatchHost("string")
                            .name("name")
                            .enabled(true)
                            .addHeader(
                                BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                    .name("name")
                                    .type(BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchPath("string")
                            .build()
                    )
                    .build()
            )
        assertThat(boxStartResponse.sizeClass()).contains("size_class")
        assertThat(boxStartResponse.snapshotId()).contains("snapshot_id")
        assertThat(boxStartResponse.status()).contains("status")
        assertThat(boxStartResponse.statusMessage()).contains("status_message")
        assertThat(boxStartResponse.stoppedAt()).contains("stopped_at")
        assertThat(boxStartResponse.updatedAt()).contains("updated_at")
        assertThat(boxStartResponse.updatedBy()).contains("updated_by")
        assertThat(boxStartResponse.vcpus()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val boxStartResponse =
            BoxStartResponse.builder()
                .id("id")
                .createdAt("created_at")
                .createdBy("created_by")
                .dataplaneUrl("dataplane_url")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .name("name")
                .proxyConfig(
                    BoxStartResponse.ProxyConfig.builder()
                        .accessControl(
                            BoxStartResponse.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxStartResponse.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxStartResponse.ProxyConfig.Callback.RequestHeader.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxStartResponse.ProxyConfig.Rule.builder()
                                .addMatchHost("string")
                                .name("name")
                                .enabled(true)
                                .addHeader(
                                    BoxStartResponse.ProxyConfig.Rule.Header.builder()
                                        .name("name")
                                        .type(
                                            BoxStartResponse.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchPath("string")
                                .build()
                        )
                        .build()
                )
                .sizeClass("size_class")
                .snapshotId("snapshot_id")
                .status("status")
                .statusMessage("status_message")
                .stoppedAt("stopped_at")
                .updatedAt("updated_at")
                .updatedBy("updated_by")
                .vcpus(0L)
                .build()

        val roundtrippedBoxStartResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(boxStartResponse),
                jacksonTypeRef<BoxStartResponse>(),
            )

        assertThat(roundtrippedBoxStartResponse).isEqualTo(boxStartResponse)
    }
}
