// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sandboxes.boxes

import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BoxUpdateParamsTest {

    @Test
    fun create() {
        BoxUpdateParams.builder()
            .pathName("name")
            .deleteAfterStopSeconds(0L)
            .fsCapacityBytes(0L)
            .idleTtlSeconds(0L)
            .memBytes(0L)
            .bodyName("name")
            .proxyConfig(
                BoxUpdateParams.ProxyConfig.builder()
                    .accessControl(
                        BoxUpdateParams.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxUpdateParams.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxUpdateParams.ProxyConfig.Callback.RequestHeader.builder()
                                    .bodyName("name")
                                    .type(
                                        BoxUpdateParams.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxUpdateParams.ProxyConfig.Rule.builder()
                            .bodyName("name")
                            .aws(
                                BoxUpdateParams.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxUpdateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxUpdateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .addHeader(
                                BoxUpdateParams.ProxyConfig.Rule.Header.builder()
                                    .bodyName("name")
                                    .type(BoxUpdateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
            .addTagValueId("string")
            .vcpus(0L)
            .build()
    }

    @Test
    fun pathParams() {
        val params = BoxUpdateParams.builder().pathName("name").build()

        assertThat(params._pathParam(0)).isEqualTo("name")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            BoxUpdateParams.builder()
                .pathName("name")
                .deleteAfterStopSeconds(0L)
                .fsCapacityBytes(0L)
                .idleTtlSeconds(0L)
                .memBytes(0L)
                .bodyName("name")
                .proxyConfig(
                    BoxUpdateParams.ProxyConfig.builder()
                        .accessControl(
                            BoxUpdateParams.ProxyConfig.AccessControl.builder()
                                .addAllowList("string")
                                .addDenyList("string")
                                .build()
                        )
                        .addCallback(
                            BoxUpdateParams.ProxyConfig.Callback.builder()
                                .addMatchHost("string")
                                .ttlSeconds(60L)
                                .url("url")
                                .fullRequest(true)
                                .addRequestHeader(
                                    BoxUpdateParams.ProxyConfig.Callback.RequestHeader.builder()
                                        .bodyName("name")
                                        .type(
                                            BoxUpdateParams.ProxyConfig.Callback.RequestHeader.Type
                                                .PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .addNoProxy("string")
                        .addRule(
                            BoxUpdateParams.ProxyConfig.Rule.builder()
                                .bodyName("name")
                                .aws(
                                    BoxUpdateParams.ProxyConfig.Rule.Aws.builder()
                                        .accessKeyId(
                                            BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                .builder()
                                                .type(
                                                    BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .secretAccessKey(
                                            BoxUpdateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                .builder()
                                                .type(
                                                    BoxUpdateParams.ProxyConfig.Rule.Aws
                                                        .SecretAccessKey
                                                        .Type
                                                        .PLAINTEXT
                                                )
                                                .isSet(true)
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                                .enabled(true)
                                .addHeader(
                                    BoxUpdateParams.ProxyConfig.Rule.Header.builder()
                                        .bodyName("name")
                                        .type(
                                            BoxUpdateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT
                                        )
                                        .isSet(true)
                                        .value("value")
                                        .build()
                                )
                                .addMatchHost("string")
                                .addMatchPath("string")
                                .type("type")
                                .build()
                        )
                        .build()
                )
                .addTagValueId("string")
                .vcpus(0L)
                .build()

        val body = params._body()

        assertThat(body.deleteAfterStopSeconds()).contains(0L)
        assertThat(body.fsCapacityBytes()).contains(0L)
        assertThat(body.idleTtlSeconds()).contains(0L)
        assertThat(body.memBytes()).contains(0L)
        assertThat(body.bodyName()).contains("name")
        assertThat(body.proxyConfig())
            .contains(
                BoxUpdateParams.ProxyConfig.builder()
                    .accessControl(
                        BoxUpdateParams.ProxyConfig.AccessControl.builder()
                            .addAllowList("string")
                            .addDenyList("string")
                            .build()
                    )
                    .addCallback(
                        BoxUpdateParams.ProxyConfig.Callback.builder()
                            .addMatchHost("string")
                            .ttlSeconds(60L)
                            .url("url")
                            .fullRequest(true)
                            .addRequestHeader(
                                BoxUpdateParams.ProxyConfig.Callback.RequestHeader.builder()
                                    .bodyName("name")
                                    .type(
                                        BoxUpdateParams.ProxyConfig.Callback.RequestHeader.Type
                                            .PLAINTEXT
                                    )
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .addNoProxy("string")
                    .addRule(
                        BoxUpdateParams.ProxyConfig.Rule.builder()
                            .bodyName("name")
                            .aws(
                                BoxUpdateParams.ProxyConfig.Rule.Aws.builder()
                                    .accessKeyId(
                                        BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId.builder()
                                            .type(
                                                BoxUpdateParams.ProxyConfig.Rule.Aws.AccessKeyId
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .secretAccessKey(
                                        BoxUpdateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                            .builder()
                                            .type(
                                                BoxUpdateParams.ProxyConfig.Rule.Aws.SecretAccessKey
                                                    .Type
                                                    .PLAINTEXT
                                            )
                                            .isSet(true)
                                            .value("value")
                                            .build()
                                    )
                                    .build()
                            )
                            .enabled(true)
                            .addHeader(
                                BoxUpdateParams.ProxyConfig.Rule.Header.builder()
                                    .bodyName("name")
                                    .type(BoxUpdateParams.ProxyConfig.Rule.Header.Type.PLAINTEXT)
                                    .isSet(true)
                                    .value("value")
                                    .build()
                            )
                            .addMatchHost("string")
                            .addMatchPath("string")
                            .type("type")
                            .build()
                    )
                    .build()
            )
        assertThat(body.tagValueIds().getOrNull()).containsExactly("string")
        assertThat(body.vcpus()).contains(0L)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = BoxUpdateParams.builder().pathName("name").build()

        val body = params._body()
    }
}
