// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.issues

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.JsonValue
import com.langchain.smith.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IssueTest {

    @Test
    fun create() {
        val issue =
            Issue.builder()
                .id("id")
                .actions(JsonValue.from(mapOf<String, Any>()))
                .autoResolutionEvidence(JsonValue.from(mapOf<String, Any>()))
                .autoResolutionState("auto_resolution_state")
                .createdAt("created_at")
                .description("description")
                .evidence(
                    Issue.Evidence.builder()
                        .type(Issue.Evidence.Type.SERIES)
                        .series(
                            Issue.Evidence.Series.builder()
                                .metricDefinition(
                                    Issue.Evidence.Series.MetricDefinition.builder()
                                        .type(Issue.Evidence.Series.MetricDefinition.Type.COUNT)
                                        .denominator(
                                            Issue.Evidence.Series.MetricDefinition.Denominator
                                                .builder()
                                                .type(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Type
                                                        .COUNT
                                                )
                                                .entity(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Entity
                                                        .RUN
                                                )
                                                .field(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Field
                                                        .LATENCY_SECONDS
                                                )
                                                .filter("filter")
                                                .params(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Params
                                                        .builder()
                                                        .bucketCount(0L)
                                                        .feedbackKey("feedback_key")
                                                        .p(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .entity(Issue.Evidence.Series.MetricDefinition.Entity.RUN)
                                        .field(
                                            Issue.Evidence.Series.MetricDefinition.Field
                                                .LATENCY_SECONDS
                                        )
                                        .numerator(
                                            Issue.Evidence.Series.MetricDefinition.Numerator
                                                .builder()
                                                .type(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Type
                                                        .COUNT
                                                )
                                                .entity(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Entity
                                                        .RUN
                                                )
                                                .field(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Field
                                                        .LATENCY_SECONDS
                                                )
                                                .filter("filter")
                                                .params(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Params
                                                        .builder()
                                                        .bucketCount(0L)
                                                        .feedbackKey("feedback_key")
                                                        .p(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .params(
                                            Issue.Evidence.Series.MetricDefinition.Params.builder()
                                                .bucketCount(0L)
                                                .feedbackKey("feedback_key")
                                                .p(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .runFilter("run_filter")
                                .windowEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .windowStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .firstSeenAt("first_seen_at")
                .fixBranch("fix_branch")
                .fixDispatchedAt("fix_dispatched_at")
                .fixPrNumber(0L)
                .fixPrompt("fix_prompt")
                .fixVerification(
                    Issue.FixVerification.builder()
                        .attempt(0L)
                        .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .parentDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .previewDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .previewExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .reason("reason")
                        .addRootTraceId("string")
                        .status(Issue.FixVerification.Status.AWAITING_PREVIEW)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addFix(
                    Issue.Fix.builder()
                        .id("id")
                        .branch("branch")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .prNumber(0L)
                        .repoUrl("repo_url")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .lastSeenAt("last_seen_at")
                .linearContext(
                    Issue.LinearContext.builder()
                        .addGitHubPrUrl("string")
                        .workflowState("workflow_state")
                        .build()
                )
                .linearSync(
                    Issue.LinearSync.builder()
                        .identifier("identifier")
                        .issueId("issue_id")
                        .lastAttemptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .lastError("last_error")
                        .lastSyncedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .linearIssueId("linear_issue_id")
                        .state(Issue.LinearSync.State.PENDING)
                        .url("url")
                        .build()
                )
                .name("name")
                .addProposedContextFix(JsonValue.from(mapOf<String, Any>()))
                .addProposedExample(JsonValue.from(mapOf<String, Any>()))
                .proposedFix("proposed_fix")
                .addProposedPromptFix(JsonValue.from(mapOf<String, Any>()))
                .recurrencesSinceWatching(0L)
                .sessionId("session_id")
                .severity(Issue.Severity._0)
                .status(Issue.Status.OPEN)
                .addTag("string")
                .tenantId("tenant_id")
                .traces(JsonValue.from(mapOf<String, Any>()))
                .updatedAt("updated_at")
                .validationResult(
                    Issue.ValidationResult.builder()
                        .activeRevisionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .deploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .outcome(Issue.ValidationResult.Outcome.REPRODUCED)
                        .reason("reason")
                        .addRootTraceId("string")
                        .build()
                )
                .watchingSince("watching_since")
                .build()

        assertThat(issue.id()).contains("id")
        assertThat(issue._actions()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue._autoResolutionEvidence()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue.autoResolutionState()).contains("auto_resolution_state")
        assertThat(issue.createdAt()).contains("created_at")
        assertThat(issue.description()).contains("description")
        assertThat(issue.evidence())
            .contains(
                Issue.Evidence.builder()
                    .type(Issue.Evidence.Type.SERIES)
                    .series(
                        Issue.Evidence.Series.builder()
                            .metricDefinition(
                                Issue.Evidence.Series.MetricDefinition.builder()
                                    .type(Issue.Evidence.Series.MetricDefinition.Type.COUNT)
                                    .denominator(
                                        Issue.Evidence.Series.MetricDefinition.Denominator.builder()
                                            .type(
                                                Issue.Evidence.Series.MetricDefinition.Denominator
                                                    .Type
                                                    .COUNT
                                            )
                                            .entity(
                                                Issue.Evidence.Series.MetricDefinition.Denominator
                                                    .Entity
                                                    .RUN
                                            )
                                            .field(
                                                Issue.Evidence.Series.MetricDefinition.Denominator
                                                    .Field
                                                    .LATENCY_SECONDS
                                            )
                                            .filter("filter")
                                            .params(
                                                Issue.Evidence.Series.MetricDefinition.Denominator
                                                    .Params
                                                    .builder()
                                                    .bucketCount(0L)
                                                    .feedbackKey("feedback_key")
                                                    .p(0.0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .entity(Issue.Evidence.Series.MetricDefinition.Entity.RUN)
                                    .field(
                                        Issue.Evidence.Series.MetricDefinition.Field.LATENCY_SECONDS
                                    )
                                    .numerator(
                                        Issue.Evidence.Series.MetricDefinition.Numerator.builder()
                                            .type(
                                                Issue.Evidence.Series.MetricDefinition.Numerator
                                                    .Type
                                                    .COUNT
                                            )
                                            .entity(
                                                Issue.Evidence.Series.MetricDefinition.Numerator
                                                    .Entity
                                                    .RUN
                                            )
                                            .field(
                                                Issue.Evidence.Series.MetricDefinition.Numerator
                                                    .Field
                                                    .LATENCY_SECONDS
                                            )
                                            .filter("filter")
                                            .params(
                                                Issue.Evidence.Series.MetricDefinition.Numerator
                                                    .Params
                                                    .builder()
                                                    .bucketCount(0L)
                                                    .feedbackKey("feedback_key")
                                                    .p(0.0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .params(
                                        Issue.Evidence.Series.MetricDefinition.Params.builder()
                                            .bucketCount(0L)
                                            .feedbackKey("feedback_key")
                                            .p(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .runFilter("run_filter")
                            .windowEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .windowStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
        assertThat(issue.firstSeenAt()).contains("first_seen_at")
        assertThat(issue.fixBranch()).contains("fix_branch")
        assertThat(issue.fixDispatchedAt()).contains("fix_dispatched_at")
        assertThat(issue.fixPrNumber()).contains(0L)
        assertThat(issue.fixPrompt()).contains("fix_prompt")
        assertThat(issue.fixVerification())
            .contains(
                Issue.FixVerification.builder()
                    .attempt(0L)
                    .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .parentDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .previewDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .previewExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .reason("reason")
                    .addRootTraceId("string")
                    .status(Issue.FixVerification.Status.AWAITING_PREVIEW)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(issue.fixes().getOrNull())
            .containsExactly(
                Issue.Fix.builder()
                    .id("id")
                    .branch("branch")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .prNumber(0L)
                    .repoUrl("repo_url")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(issue.lastSeenAt()).contains("last_seen_at")
        assertThat(issue.linearContext())
            .contains(
                Issue.LinearContext.builder()
                    .addGitHubPrUrl("string")
                    .workflowState("workflow_state")
                    .build()
            )
        assertThat(issue.linearSync())
            .contains(
                Issue.LinearSync.builder()
                    .identifier("identifier")
                    .issueId("issue_id")
                    .lastAttemptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .lastError("last_error")
                    .lastSyncedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .linearIssueId("linear_issue_id")
                    .state(Issue.LinearSync.State.PENDING)
                    .url("url")
                    .build()
            )
        assertThat(issue.name()).contains("name")
        assertThat(issue.proposedContextFixes().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue.proposedExamples().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue.proposedFix()).contains("proposed_fix")
        assertThat(issue.proposedPromptFixes().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue.recurrencesSinceWatching()).contains(0L)
        assertThat(issue.sessionId()).contains("session_id")
        assertThat(issue.severity()).contains(Issue.Severity._0)
        assertThat(issue.status()).contains(Issue.Status.OPEN)
        assertThat(issue.tags().getOrNull()).containsExactly("string")
        assertThat(issue.tenantId()).contains("tenant_id")
        assertThat(issue._traces()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(issue.updatedAt()).contains("updated_at")
        assertThat(issue.validationResult())
            .contains(
                Issue.ValidationResult.builder()
                    .activeRevisionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .deploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .outcome(Issue.ValidationResult.Outcome.REPRODUCED)
                    .reason("reason")
                    .addRootTraceId("string")
                    .build()
            )
        assertThat(issue.watchingSince()).contains("watching_since")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val issue =
            Issue.builder()
                .id("id")
                .actions(JsonValue.from(mapOf<String, Any>()))
                .autoResolutionEvidence(JsonValue.from(mapOf<String, Any>()))
                .autoResolutionState("auto_resolution_state")
                .createdAt("created_at")
                .description("description")
                .evidence(
                    Issue.Evidence.builder()
                        .type(Issue.Evidence.Type.SERIES)
                        .series(
                            Issue.Evidence.Series.builder()
                                .metricDefinition(
                                    Issue.Evidence.Series.MetricDefinition.builder()
                                        .type(Issue.Evidence.Series.MetricDefinition.Type.COUNT)
                                        .denominator(
                                            Issue.Evidence.Series.MetricDefinition.Denominator
                                                .builder()
                                                .type(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Type
                                                        .COUNT
                                                )
                                                .entity(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Entity
                                                        .RUN
                                                )
                                                .field(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Field
                                                        .LATENCY_SECONDS
                                                )
                                                .filter("filter")
                                                .params(
                                                    Issue.Evidence.Series.MetricDefinition
                                                        .Denominator
                                                        .Params
                                                        .builder()
                                                        .bucketCount(0L)
                                                        .feedbackKey("feedback_key")
                                                        .p(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .entity(Issue.Evidence.Series.MetricDefinition.Entity.RUN)
                                        .field(
                                            Issue.Evidence.Series.MetricDefinition.Field
                                                .LATENCY_SECONDS
                                        )
                                        .numerator(
                                            Issue.Evidence.Series.MetricDefinition.Numerator
                                                .builder()
                                                .type(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Type
                                                        .COUNT
                                                )
                                                .entity(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Entity
                                                        .RUN
                                                )
                                                .field(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Field
                                                        .LATENCY_SECONDS
                                                )
                                                .filter("filter")
                                                .params(
                                                    Issue.Evidence.Series.MetricDefinition.Numerator
                                                        .Params
                                                        .builder()
                                                        .bucketCount(0L)
                                                        .feedbackKey("feedback_key")
                                                        .p(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .params(
                                            Issue.Evidence.Series.MetricDefinition.Params.builder()
                                                .bucketCount(0L)
                                                .feedbackKey("feedback_key")
                                                .p(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .runFilter("run_filter")
                                .windowEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .windowStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .firstSeenAt("first_seen_at")
                .fixBranch("fix_branch")
                .fixDispatchedAt("fix_dispatched_at")
                .fixPrNumber(0L)
                .fixPrompt("fix_prompt")
                .fixVerification(
                    Issue.FixVerification.builder()
                        .attempt(0L)
                        .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .parentDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .previewDeploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .previewExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .reason("reason")
                        .addRootTraceId("string")
                        .status(Issue.FixVerification.Status.AWAITING_PREVIEW)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addFix(
                    Issue.Fix.builder()
                        .id("id")
                        .branch("branch")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .prNumber(0L)
                        .repoUrl("repo_url")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .lastSeenAt("last_seen_at")
                .linearContext(
                    Issue.LinearContext.builder()
                        .addGitHubPrUrl("string")
                        .workflowState("workflow_state")
                        .build()
                )
                .linearSync(
                    Issue.LinearSync.builder()
                        .identifier("identifier")
                        .issueId("issue_id")
                        .lastAttemptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .lastError("last_error")
                        .lastSyncedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .linearIssueId("linear_issue_id")
                        .state(Issue.LinearSync.State.PENDING)
                        .url("url")
                        .build()
                )
                .name("name")
                .addProposedContextFix(JsonValue.from(mapOf<String, Any>()))
                .addProposedExample(JsonValue.from(mapOf<String, Any>()))
                .proposedFix("proposed_fix")
                .addProposedPromptFix(JsonValue.from(mapOf<String, Any>()))
                .recurrencesSinceWatching(0L)
                .sessionId("session_id")
                .severity(Issue.Severity._0)
                .status(Issue.Status.OPEN)
                .addTag("string")
                .tenantId("tenant_id")
                .traces(JsonValue.from(mapOf<String, Any>()))
                .updatedAt("updated_at")
                .validationResult(
                    Issue.ValidationResult.builder()
                        .activeRevisionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .baselineExperimentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .datasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .deploymentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .outcome(Issue.ValidationResult.Outcome.REPRODUCED)
                        .reason("reason")
                        .addRootTraceId("string")
                        .build()
                )
                .watchingSince("watching_since")
                .build()

        val roundtrippedIssue =
            jsonMapper.readValue(jsonMapper.writeValueAsString(issue), jacksonTypeRef<Issue>())

        assertThat(roundtrippedIssue).isEqualTo(issue)
    }
}
