// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.annotationqueues

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.JsonValue
import com.langchain.smith.core.jsonMapper
import com.langchain.smith.models.runs.RunTypeEnum
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RunSchemaWithAnnotationQueueInfoTest {

    @Test
    fun create() {
        val runSchemaWithAnnotationQueueInfo =
            RunSchemaWithAnnotationQueueInfo.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .appPath("app_path")
                .dottedOrder("dotted_order")
                .name("name")
                .queueRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .runType(RunTypeEnum.TOOL)
                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .status("status")
                .traceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addChildRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .completionCost("completion_cost")
                .completionCostDetails(
                    RunSchemaWithAnnotationQueueInfo.CompletionCostDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .completionTokenDetails(
                    RunSchemaWithAnnotationQueueInfo.CompletionTokenDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .completionTokens(0L)
                .addDirectChildRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .effectiveAddedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .endTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .error("error")
                .addEvent(JsonValue.from(mapOf<String, Any>()))
                .executionOrder(1L)
                .extra(JsonValue.from(mapOf<String, Any>()))
                .feedbackStats(
                    RunSchemaWithAnnotationQueueInfo.FeedbackStats.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .firstTokenTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .inDataset(true)
                .inputs(JsonValue.from(mapOf<String, Any>()))
                .inputsPreview("inputs_preview")
                .inputsS3Urls(JsonValue.from(mapOf<String, Any>()))
                .lastQueuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .lastReviewedTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .manifestId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .manifestS3Id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .outputs(JsonValue.from(mapOf<String, Any>()))
                .outputsPreview("outputs_preview")
                .outputsS3Urls(JsonValue.from(mapOf<String, Any>()))
                .parentRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addParentRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .priceModelId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .promptCost("prompt_cost")
                .promptCostDetails(
                    RunSchemaWithAnnotationQueueInfo.PromptCostDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .promptTokenDetails(
                    RunSchemaWithAnnotationQueueInfo.PromptTokenDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .promptTokens(0L)
                .referenceDatasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .referenceExampleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .s3Urls(JsonValue.from(mapOf<String, Any>()))
                .serialized(JsonValue.from(mapOf<String, Any>()))
                .shareToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .startTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addTag("string")
                .threadId("thread_id")
                .totalCost("total_cost")
                .totalTokens(0L)
                .traceFirstReceivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceMaxStartTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceMinStartTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceTier(RunSchemaWithAnnotationQueueInfo.TraceTier.LONGLIVED)
                .traceUpgrade(true)
                .ttlSeconds(0L)
                .build()

        assertThat(runSchemaWithAnnotationQueueInfo.id())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.appPath()).isEqualTo("app_path")
        assertThat(runSchemaWithAnnotationQueueInfo.dottedOrder()).isEqualTo("dotted_order")
        assertThat(runSchemaWithAnnotationQueueInfo.name()).isEqualTo("name")
        assertThat(runSchemaWithAnnotationQueueInfo.queueRunId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.runType()).isEqualTo(RunTypeEnum.TOOL)
        assertThat(runSchemaWithAnnotationQueueInfo.sessionId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.status()).isEqualTo("status")
        assertThat(runSchemaWithAnnotationQueueInfo.traceId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.addedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.childRunIds().getOrNull())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.completionCost()).contains("completion_cost")
        assertThat(runSchemaWithAnnotationQueueInfo.completionCostDetails())
            .contains(
                RunSchemaWithAnnotationQueueInfo.CompletionCostDetails.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(runSchemaWithAnnotationQueueInfo.completionTokenDetails())
            .contains(
                RunSchemaWithAnnotationQueueInfo.CompletionTokenDetails.builder()
                    .putAdditionalProperty("foo", JsonValue.from(0))
                    .build()
            )
        assertThat(runSchemaWithAnnotationQueueInfo.completionTokens()).contains(0L)
        assertThat(runSchemaWithAnnotationQueueInfo.directChildRunIds().getOrNull())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.effectiveAddedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.endTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.error()).contains("error")
        assertThat(runSchemaWithAnnotationQueueInfo.events().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.executionOrder()).contains(1L)
        assertThat(runSchemaWithAnnotationQueueInfo._extra())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.feedbackStats())
            .contains(
                RunSchemaWithAnnotationQueueInfo.FeedbackStats.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(runSchemaWithAnnotationQueueInfo.firstTokenTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.inDataset()).contains(true)
        assertThat(runSchemaWithAnnotationQueueInfo._inputs())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.inputsPreview()).contains("inputs_preview")
        assertThat(runSchemaWithAnnotationQueueInfo._inputsS3Urls())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.lastQueuedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.lastReviewedTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.manifestId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.manifestS3Id())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo._outputs())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.outputsPreview()).contains("outputs_preview")
        assertThat(runSchemaWithAnnotationQueueInfo._outputsS3Urls())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.parentRunId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.parentRunIds().getOrNull())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.priceModelId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.promptCost()).contains("prompt_cost")
        assertThat(runSchemaWithAnnotationQueueInfo.promptCostDetails())
            .contains(
                RunSchemaWithAnnotationQueueInfo.PromptCostDetails.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(runSchemaWithAnnotationQueueInfo.promptTokenDetails())
            .contains(
                RunSchemaWithAnnotationQueueInfo.PromptTokenDetails.builder()
                    .putAdditionalProperty("foo", JsonValue.from(0))
                    .build()
            )
        assertThat(runSchemaWithAnnotationQueueInfo.promptTokens()).contains(0L)
        assertThat(runSchemaWithAnnotationQueueInfo.referenceDatasetId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.referenceExampleId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo._s3Urls())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo._serialized())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(runSchemaWithAnnotationQueueInfo.shareToken())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(runSchemaWithAnnotationQueueInfo.startTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.tags().getOrNull()).containsExactly("string")
        assertThat(runSchemaWithAnnotationQueueInfo.threadId()).contains("thread_id")
        assertThat(runSchemaWithAnnotationQueueInfo.totalCost()).contains("total_cost")
        assertThat(runSchemaWithAnnotationQueueInfo.totalTokens()).contains(0L)
        assertThat(runSchemaWithAnnotationQueueInfo.traceFirstReceivedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.traceMaxStartTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.traceMinStartTime())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(runSchemaWithAnnotationQueueInfo.traceTier())
            .contains(RunSchemaWithAnnotationQueueInfo.TraceTier.LONGLIVED)
        assertThat(runSchemaWithAnnotationQueueInfo.traceUpgrade()).contains(true)
        assertThat(runSchemaWithAnnotationQueueInfo.ttlSeconds()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val runSchemaWithAnnotationQueueInfo =
            RunSchemaWithAnnotationQueueInfo.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .appPath("app_path")
                .dottedOrder("dotted_order")
                .name("name")
                .queueRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .runType(RunTypeEnum.TOOL)
                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .status("status")
                .traceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addChildRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .completionCost("completion_cost")
                .completionCostDetails(
                    RunSchemaWithAnnotationQueueInfo.CompletionCostDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .completionTokenDetails(
                    RunSchemaWithAnnotationQueueInfo.CompletionTokenDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .completionTokens(0L)
                .addDirectChildRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .effectiveAddedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .endTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .error("error")
                .addEvent(JsonValue.from(mapOf<String, Any>()))
                .executionOrder(1L)
                .extra(JsonValue.from(mapOf<String, Any>()))
                .feedbackStats(
                    RunSchemaWithAnnotationQueueInfo.FeedbackStats.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .firstTokenTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .inDataset(true)
                .inputs(JsonValue.from(mapOf<String, Any>()))
                .inputsPreview("inputs_preview")
                .inputsS3Urls(JsonValue.from(mapOf<String, Any>()))
                .lastQueuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .lastReviewedTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .manifestId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .manifestS3Id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .outputs(JsonValue.from(mapOf<String, Any>()))
                .outputsPreview("outputs_preview")
                .outputsS3Urls(JsonValue.from(mapOf<String, Any>()))
                .parentRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addParentRunId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .priceModelId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .promptCost("prompt_cost")
                .promptCostDetails(
                    RunSchemaWithAnnotationQueueInfo.PromptCostDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .promptTokenDetails(
                    RunSchemaWithAnnotationQueueInfo.PromptTokenDetails.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .promptTokens(0L)
                .referenceDatasetId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .referenceExampleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .s3Urls(JsonValue.from(mapOf<String, Any>()))
                .serialized(JsonValue.from(mapOf<String, Any>()))
                .shareToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .startTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addTag("string")
                .threadId("thread_id")
                .totalCost("total_cost")
                .totalTokens(0L)
                .traceFirstReceivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceMaxStartTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceMinStartTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .traceTier(RunSchemaWithAnnotationQueueInfo.TraceTier.LONGLIVED)
                .traceUpgrade(true)
                .ttlSeconds(0L)
                .build()

        val roundtrippedRunSchemaWithAnnotationQueueInfo =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(runSchemaWithAnnotationQueueInfo),
                jacksonTypeRef<RunSchemaWithAnnotationQueueInfo>(),
            )

        assertThat(roundtrippedRunSchemaWithAnnotationQueueInfo)
            .isEqualTo(runSchemaWithAnnotationQueueInfo)
    }
}
