// File generated from our OpenAPI spec by Stainless.

package com.langchain.smith.models.sessions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.langchain.smith.core.JsonValue
import com.langchain.smith.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomChartsSectionTest {

    @Test
    fun create() {
        val customChartsSection =
            CustomChartsSection.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addChart(
                    CustomChartsSection.Chart.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .chartType(CustomChartsSection.Chart.ChartType.LINE)
                        .addData(
                            CustomChartsSection.Chart.Data.builder()
                                .seriesId("series_id")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .value(0.0)
                                .group("group")
                                .build()
                        )
                        .index(0L)
                        .addSeries(
                            CustomChartsSection.Chart.Series.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .feedbackKey("feedback_key")
                                .filterDefinition(
                                    CustomChartsSection.Chart.Series.FilterDefinition
                                        .CustomChartFilterByTracingProject
                                        .builder()
                                        .addProjectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .runFilter("run_filter")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .filters(
                                    CustomChartsSection.Chart.Series.Filters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .groupBy(
                                    CustomChartsSection.Chart.Series.GroupBy.builder()
                                        .attribute(
                                            CustomChartsSection.Chart.Series.GroupBy.Attribute.NAME
                                        )
                                        .maxGroups(0L)
                                        .path("path")
                                        .setBy(
                                            CustomChartsSection.Chart.Series.GroupBy.SetBy.SECTION
                                        )
                                        .build()
                                )
                                .addGroupByDefinition(
                                    CustomChartsSection.Chart.Series.GroupByDefinition
                                        .CustomChartGroupByPlain
                                        .builder()
                                        .attribute(
                                            CustomChartsSection.Chart.Series.GroupByDefinition
                                                .CustomChartGroupByPlain
                                                .Attribute
                                                .NAME
                                        )
                                        .build()
                                )
                                .metadata(
                                    CustomChartsSection.Chart.Series.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .metric(CustomChartsSection.Chart.Series.Metric.RUN_COUNT)
                                .metricDefinition(
                                    CustomChartsSection.Chart.Series.MetricDefinition
                                        .CustomChartMetricCount
                                        .builder()
                                        .filter("filter")
                                        .type(
                                            CustomChartsSection.Chart.Series.MetricDefinition
                                                .CustomChartMetricCount
                                                .Type
                                                .COUNT
                                        )
                                        .build()
                                )
                                .projectMetric(
                                    CustomChartsSection.Chart.Series.ProjectMetric.MEMORY_USAGE
                                )
                                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .title("title")
                        .commonFilters(
                            CustomChartsSection.Chart.CommonFilters.builder()
                                .filter("filter")
                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .traceFilter("trace_filter")
                                .treeFilter("tree_filter")
                                .build()
                        )
                        .description("description")
                        .metadata(
                            CustomChartsSection.Chart.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .title("title")
                .description("description")
                .index(0L)
                .layout(
                    CustomChartsSection.Layout.builder()
                        .breakpoints(
                            CustomChartsSection.Layout.Breakpoints.builder()
                                .md(
                                    CustomChartsSection.Layout.Breakpoints.Md.builder()
                                        .addRow(
                                            CustomChartsSection.Layout.Breakpoints.Md.Row.builder()
                                                .heightUnits(0L)
                                                .addItem(
                                                    CustomChartsSection.Layout.Breakpoints.Md.Row
                                                        .Item
                                                        .builder()
                                                        .chartId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .widthUnits(20L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .sm(
                                    CustomChartsSection.Layout.Breakpoints.Sm.builder()
                                        .addRow(
                                            CustomChartsSection.Layout.Breakpoints.Sm.Row.builder()
                                                .heightUnits(0L)
                                                .addItem(
                                                    CustomChartsSection.Layout.Breakpoints.Sm.Row
                                                        .Item
                                                        .builder()
                                                        .chartId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .widthUnits(20L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addSubSection(
                    CustomChartsSection.SubSection.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addChart(
                            CustomChartsSection.SubSection.Chart.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .chartType(CustomChartsSection.SubSection.Chart.ChartType.LINE)
                                .addData(
                                    CustomChartsSection.SubSection.Chart.Data.builder()
                                        .seriesId("series_id")
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .value(0.0)
                                        .group("group")
                                        .build()
                                )
                                .index(0L)
                                .addSeries(
                                    CustomChartsSection.SubSection.Chart.Series.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .feedbackKey("feedback_key")
                                        .filterDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .FilterDefinition
                                                .CustomChartFilterByTracingProject
                                                .builder()
                                                .addProjectId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .runFilter("run_filter")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .filters(
                                            CustomChartsSection.SubSection.Chart.Series.Filters
                                                .builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .groupBy(
                                            CustomChartsSection.SubSection.Chart.Series.GroupBy
                                                .builder()
                                                .attribute(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupBy
                                                        .Attribute
                                                        .NAME
                                                )
                                                .maxGroups(0L)
                                                .path("path")
                                                .setBy(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupBy
                                                        .SetBy
                                                        .SECTION
                                                )
                                                .build()
                                        )
                                        .addGroupByDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .GroupByDefinition
                                                .CustomChartGroupByPlain
                                                .builder()
                                                .attribute(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupByDefinition
                                                        .CustomChartGroupByPlain
                                                        .Attribute
                                                        .NAME
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            CustomChartsSection.SubSection.Chart.Series.Metadata
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .metric(
                                            CustomChartsSection.SubSection.Chart.Series.Metric
                                                .RUN_COUNT
                                        )
                                        .metricDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .MetricDefinition
                                                .CustomChartMetricCount
                                                .builder()
                                                .filter("filter")
                                                .type(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .MetricDefinition
                                                        .CustomChartMetricCount
                                                        .Type
                                                        .COUNT
                                                )
                                                .build()
                                        )
                                        .projectMetric(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .ProjectMetric
                                                .MEMORY_USAGE
                                        )
                                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .title("title")
                                .commonFilters(
                                    CustomChartsSection.SubSection.Chart.CommonFilters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .description("description")
                                .metadata(
                                    CustomChartsSection.SubSection.Chart.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .index(0L)
                        .title("title")
                        .description("description")
                        .build()
                )
                .build()

        assertThat(customChartsSection.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(customChartsSection.charts())
            .containsExactly(
                CustomChartsSection.Chart.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .chartType(CustomChartsSection.Chart.ChartType.LINE)
                    .addData(
                        CustomChartsSection.Chart.Data.builder()
                            .seriesId("series_id")
                            .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .value(0.0)
                            .group("group")
                            .build()
                    )
                    .index(0L)
                    .addSeries(
                        CustomChartsSection.Chart.Series.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .feedbackKey("feedback_key")
                            .filterDefinition(
                                CustomChartsSection.Chart.Series.FilterDefinition
                                    .CustomChartFilterByTracingProject
                                    .builder()
                                    .addProjectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .runFilter("run_filter")
                                    .traceFilter("trace_filter")
                                    .treeFilter("tree_filter")
                                    .build()
                            )
                            .filters(
                                CustomChartsSection.Chart.Series.Filters.builder()
                                    .filter("filter")
                                    .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .traceFilter("trace_filter")
                                    .treeFilter("tree_filter")
                                    .build()
                            )
                            .groupBy(
                                CustomChartsSection.Chart.Series.GroupBy.builder()
                                    .attribute(
                                        CustomChartsSection.Chart.Series.GroupBy.Attribute.NAME
                                    )
                                    .maxGroups(0L)
                                    .path("path")
                                    .setBy(CustomChartsSection.Chart.Series.GroupBy.SetBy.SECTION)
                                    .build()
                            )
                            .addGroupByDefinition(
                                CustomChartsSection.Chart.Series.GroupByDefinition
                                    .CustomChartGroupByPlain
                                    .builder()
                                    .attribute(
                                        CustomChartsSection.Chart.Series.GroupByDefinition
                                            .CustomChartGroupByPlain
                                            .Attribute
                                            .NAME
                                    )
                                    .build()
                            )
                            .metadata(
                                CustomChartsSection.Chart.Series.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .metric(CustomChartsSection.Chart.Series.Metric.RUN_COUNT)
                            .metricDefinition(
                                CustomChartsSection.Chart.Series.MetricDefinition
                                    .CustomChartMetricCount
                                    .builder()
                                    .filter("filter")
                                    .type(
                                        CustomChartsSection.Chart.Series.MetricDefinition
                                            .CustomChartMetricCount
                                            .Type
                                            .COUNT
                                    )
                                    .build()
                            )
                            .projectMetric(
                                CustomChartsSection.Chart.Series.ProjectMetric.MEMORY_USAGE
                            )
                            .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .title("title")
                    .commonFilters(
                        CustomChartsSection.Chart.CommonFilters.builder()
                            .filter("filter")
                            .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .traceFilter("trace_filter")
                            .treeFilter("tree_filter")
                            .build()
                    )
                    .description("description")
                    .metadata(
                        CustomChartsSection.Chart.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(customChartsSection.title()).isEqualTo("title")
        assertThat(customChartsSection.description()).contains("description")
        assertThat(customChartsSection.index()).contains(0L)
        assertThat(customChartsSection.layout())
            .contains(
                CustomChartsSection.Layout.builder()
                    .breakpoints(
                        CustomChartsSection.Layout.Breakpoints.builder()
                            .md(
                                CustomChartsSection.Layout.Breakpoints.Md.builder()
                                    .addRow(
                                        CustomChartsSection.Layout.Breakpoints.Md.Row.builder()
                                            .heightUnits(0L)
                                            .addItem(
                                                CustomChartsSection.Layout.Breakpoints.Md.Row.Item
                                                    .builder()
                                                    .chartId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                    .widthUnits(20L)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .sm(
                                CustomChartsSection.Layout.Breakpoints.Sm.builder()
                                    .addRow(
                                        CustomChartsSection.Layout.Breakpoints.Sm.Row.builder()
                                            .heightUnits(0L)
                                            .addItem(
                                                CustomChartsSection.Layout.Breakpoints.Sm.Row.Item
                                                    .builder()
                                                    .chartId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                    .widthUnits(20L)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(customChartsSection.sessionId()).contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(customChartsSection.subSections().getOrNull())
            .containsExactly(
                CustomChartsSection.SubSection.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addChart(
                        CustomChartsSection.SubSection.Chart.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .chartType(CustomChartsSection.SubSection.Chart.ChartType.LINE)
                            .addData(
                                CustomChartsSection.SubSection.Chart.Data.builder()
                                    .seriesId("series_id")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .value(0.0)
                                    .group("group")
                                    .build()
                            )
                            .index(0L)
                            .addSeries(
                                CustomChartsSection.SubSection.Chart.Series.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .feedbackKey("feedback_key")
                                    .filterDefinition(
                                        CustomChartsSection.SubSection.Chart.Series.FilterDefinition
                                            .CustomChartFilterByTracingProject
                                            .builder()
                                            .addProjectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .runFilter("run_filter")
                                            .traceFilter("trace_filter")
                                            .treeFilter("tree_filter")
                                            .build()
                                    )
                                    .filters(
                                        CustomChartsSection.SubSection.Chart.Series.Filters
                                            .builder()
                                            .filter("filter")
                                            .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .traceFilter("trace_filter")
                                            .treeFilter("tree_filter")
                                            .build()
                                    )
                                    .groupBy(
                                        CustomChartsSection.SubSection.Chart.Series.GroupBy
                                            .builder()
                                            .attribute(
                                                CustomChartsSection.SubSection.Chart.Series.GroupBy
                                                    .Attribute
                                                    .NAME
                                            )
                                            .maxGroups(0L)
                                            .path("path")
                                            .setBy(
                                                CustomChartsSection.SubSection.Chart.Series.GroupBy
                                                    .SetBy
                                                    .SECTION
                                            )
                                            .build()
                                    )
                                    .addGroupByDefinition(
                                        CustomChartsSection.SubSection.Chart.Series
                                            .GroupByDefinition
                                            .CustomChartGroupByPlain
                                            .builder()
                                            .attribute(
                                                CustomChartsSection.SubSection.Chart.Series
                                                    .GroupByDefinition
                                                    .CustomChartGroupByPlain
                                                    .Attribute
                                                    .NAME
                                            )
                                            .build()
                                    )
                                    .metadata(
                                        CustomChartsSection.SubSection.Chart.Series.Metadata
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .metric(
                                        CustomChartsSection.SubSection.Chart.Series.Metric.RUN_COUNT
                                    )
                                    .metricDefinition(
                                        CustomChartsSection.SubSection.Chart.Series.MetricDefinition
                                            .CustomChartMetricCount
                                            .builder()
                                            .filter("filter")
                                            .type(
                                                CustomChartsSection.SubSection.Chart.Series
                                                    .MetricDefinition
                                                    .CustomChartMetricCount
                                                    .Type
                                                    .COUNT
                                            )
                                            .build()
                                    )
                                    .projectMetric(
                                        CustomChartsSection.SubSection.Chart.Series.ProjectMetric
                                            .MEMORY_USAGE
                                    )
                                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .title("title")
                            .commonFilters(
                                CustomChartsSection.SubSection.Chart.CommonFilters.builder()
                                    .filter("filter")
                                    .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .traceFilter("trace_filter")
                                    .treeFilter("tree_filter")
                                    .build()
                            )
                            .description("description")
                            .metadata(
                                CustomChartsSection.SubSection.Chart.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .build()
                    )
                    .index(0L)
                    .title("title")
                    .description("description")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customChartsSection =
            CustomChartsSection.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addChart(
                    CustomChartsSection.Chart.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .chartType(CustomChartsSection.Chart.ChartType.LINE)
                        .addData(
                            CustomChartsSection.Chart.Data.builder()
                                .seriesId("series_id")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .value(0.0)
                                .group("group")
                                .build()
                        )
                        .index(0L)
                        .addSeries(
                            CustomChartsSection.Chart.Series.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .feedbackKey("feedback_key")
                                .filterDefinition(
                                    CustomChartsSection.Chart.Series.FilterDefinition
                                        .CustomChartFilterByTracingProject
                                        .builder()
                                        .addProjectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .runFilter("run_filter")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .filters(
                                    CustomChartsSection.Chart.Series.Filters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .groupBy(
                                    CustomChartsSection.Chart.Series.GroupBy.builder()
                                        .attribute(
                                            CustomChartsSection.Chart.Series.GroupBy.Attribute.NAME
                                        )
                                        .maxGroups(0L)
                                        .path("path")
                                        .setBy(
                                            CustomChartsSection.Chart.Series.GroupBy.SetBy.SECTION
                                        )
                                        .build()
                                )
                                .addGroupByDefinition(
                                    CustomChartsSection.Chart.Series.GroupByDefinition
                                        .CustomChartGroupByPlain
                                        .builder()
                                        .attribute(
                                            CustomChartsSection.Chart.Series.GroupByDefinition
                                                .CustomChartGroupByPlain
                                                .Attribute
                                                .NAME
                                        )
                                        .build()
                                )
                                .metadata(
                                    CustomChartsSection.Chart.Series.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .metric(CustomChartsSection.Chart.Series.Metric.RUN_COUNT)
                                .metricDefinition(
                                    CustomChartsSection.Chart.Series.MetricDefinition
                                        .CustomChartMetricCount
                                        .builder()
                                        .filter("filter")
                                        .type(
                                            CustomChartsSection.Chart.Series.MetricDefinition
                                                .CustomChartMetricCount
                                                .Type
                                                .COUNT
                                        )
                                        .build()
                                )
                                .projectMetric(
                                    CustomChartsSection.Chart.Series.ProjectMetric.MEMORY_USAGE
                                )
                                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .title("title")
                        .commonFilters(
                            CustomChartsSection.Chart.CommonFilters.builder()
                                .filter("filter")
                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .traceFilter("trace_filter")
                                .treeFilter("tree_filter")
                                .build()
                        )
                        .description("description")
                        .metadata(
                            CustomChartsSection.Chart.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .title("title")
                .description("description")
                .index(0L)
                .layout(
                    CustomChartsSection.Layout.builder()
                        .breakpoints(
                            CustomChartsSection.Layout.Breakpoints.builder()
                                .md(
                                    CustomChartsSection.Layout.Breakpoints.Md.builder()
                                        .addRow(
                                            CustomChartsSection.Layout.Breakpoints.Md.Row.builder()
                                                .heightUnits(0L)
                                                .addItem(
                                                    CustomChartsSection.Layout.Breakpoints.Md.Row
                                                        .Item
                                                        .builder()
                                                        .chartId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .widthUnits(20L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .sm(
                                    CustomChartsSection.Layout.Breakpoints.Sm.builder()
                                        .addRow(
                                            CustomChartsSection.Layout.Breakpoints.Sm.Row.builder()
                                                .heightUnits(0L)
                                                .addItem(
                                                    CustomChartsSection.Layout.Breakpoints.Sm.Row
                                                        .Item
                                                        .builder()
                                                        .chartId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .widthUnits(20L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addSubSection(
                    CustomChartsSection.SubSection.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addChart(
                            CustomChartsSection.SubSection.Chart.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .chartType(CustomChartsSection.SubSection.Chart.ChartType.LINE)
                                .addData(
                                    CustomChartsSection.SubSection.Chart.Data.builder()
                                        .seriesId("series_id")
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .value(0.0)
                                        .group("group")
                                        .build()
                                )
                                .index(0L)
                                .addSeries(
                                    CustomChartsSection.SubSection.Chart.Series.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .feedbackKey("feedback_key")
                                        .filterDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .FilterDefinition
                                                .CustomChartFilterByTracingProject
                                                .builder()
                                                .addProjectId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .runFilter("run_filter")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .filters(
                                            CustomChartsSection.SubSection.Chart.Series.Filters
                                                .builder()
                                                .filter("filter")
                                                .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .traceFilter("trace_filter")
                                                .treeFilter("tree_filter")
                                                .build()
                                        )
                                        .groupBy(
                                            CustomChartsSection.SubSection.Chart.Series.GroupBy
                                                .builder()
                                                .attribute(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupBy
                                                        .Attribute
                                                        .NAME
                                                )
                                                .maxGroups(0L)
                                                .path("path")
                                                .setBy(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupBy
                                                        .SetBy
                                                        .SECTION
                                                )
                                                .build()
                                        )
                                        .addGroupByDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .GroupByDefinition
                                                .CustomChartGroupByPlain
                                                .builder()
                                                .attribute(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .GroupByDefinition
                                                        .CustomChartGroupByPlain
                                                        .Attribute
                                                        .NAME
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            CustomChartsSection.SubSection.Chart.Series.Metadata
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .metric(
                                            CustomChartsSection.SubSection.Chart.Series.Metric
                                                .RUN_COUNT
                                        )
                                        .metricDefinition(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .MetricDefinition
                                                .CustomChartMetricCount
                                                .builder()
                                                .filter("filter")
                                                .type(
                                                    CustomChartsSection.SubSection.Chart.Series
                                                        .MetricDefinition
                                                        .CustomChartMetricCount
                                                        .Type
                                                        .COUNT
                                                )
                                                .build()
                                        )
                                        .projectMetric(
                                            CustomChartsSection.SubSection.Chart.Series
                                                .ProjectMetric
                                                .MEMORY_USAGE
                                        )
                                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .title("title")
                                .commonFilters(
                                    CustomChartsSection.SubSection.Chart.CommonFilters.builder()
                                        .filter("filter")
                                        .addSession("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .traceFilter("trace_filter")
                                        .treeFilter("tree_filter")
                                        .build()
                                )
                                .description("description")
                                .metadata(
                                    CustomChartsSection.SubSection.Chart.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .index(0L)
                        .title("title")
                        .description("description")
                        .build()
                )
                .build()

        val roundtrippedCustomChartsSection =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customChartsSection),
                jacksonTypeRef<CustomChartsSection>(),
            )

        assertThat(roundtrippedCustomChartsSection).isEqualTo(customChartsSection)
    }
}
